### ISSUE TITLE
Customer issue: Application deployment on AWS failed

### ISSUE THREAD

**Issue by arnabold** [oracle/weblogic-kubernetes-operator#1412] opened 2020-01-31 15:10 UTC
Customer is trying to deploy a "real world" application on its pilot k8s environment on AWS. That application is correctly deployed on amazon ec2 environment, but not on the containerized environment. They had successfully deployed some test applications on the containerized environment (snoop, testwebapp, ...). 

They want to understand

-  a) if they stumbled upon a BUG
-  b) which metrics/tuning/parameters they need to monitor to successfully deploy a "real world" application on containers

Here the problem description from the customer:

> We have a problem installing a war from console. The console is blocked at the following state (upload executed with success...verifying on PV)
> An then we have an error page.
>

**Comment by mriccell** [comment] 2020-01-31 15:31
I see the following exceptions in the logs

####<Jan 28, 2020 2:32:37,702 PM GMT> <Critical> <WebLogicServer> <dwslmsb-i1wslmsb1> <i1wslmsb1> <main> <<WLS Kernel>> <> <6dc7c604-1a77-4d5f-9e5b-bafebcc5dfe8-00000005> <1580221957702> <[severity-value: 4] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000386> <Server subsystem failed. Reason: A MultiException has 2 exceptions.  They are:
1. java.nio.channels.OverlappingFileLockException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.nodemanager.NMService

A MultiException has 2 exceptions.  They are:
1. java.nio.channels.OverlappingFileLockException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.nodemanager.NMService

        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:670)
        at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
        at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
        at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)
Caused By: java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)

and  later

1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.store.admin.DefaultStoreService
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.transaction.internal.TransactionService errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.transaction.internal.TransactionService
5. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.jdbc.common.internal.JDBCService errors were found
6. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.jdbc.common.internal.JDBCService

The transaction logs can not be accessed and thus the problem with deploying the application.
This seems to be an intermittent issue since the Managed Server comes up successfully but later fails to reach the store which is on EKS.

When we tested on OKE we found a similar issue where servers would fail intermittently because files and stores could not be locked when using NFS 4.  Refer to documentation https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/persistent-storage/

Note regarding NFS: In the current GA version, the OCI Container Engine for Kubernetes supports network block storage that can be shared across nodes with access permission RWOnce (meaning that only one can write, others can read only). At this time, the WebLogic on Kubernetes domain created by the WebLogic Server Kubernetes Operator, requires a shared file system to store the WebLogic domain configuration, which MUST be accessible from all the pods across the nodes. As a workaround, you need to install an NFS server on one node and share the file system across all the nodes.

Currently, we recommend that you use NFS version 3.0 for running WebLogic Server on OCI Container Engine for Kubernetes. During certification, we found that when using NFS 4.0, the servers in the WebLogic domain went into a failed state intermittently. Because multiple threads use NFS (default store, diagnostics store, Node Manager, logging, and domain_home), there are issues when accessing the file store. These issues are removed by changing the NFS to version 3.0.

**Comment by mriccell** [comment] 2020-01-31 15:35
I see another unrelated issue where the test connections on reserve in the Data Source "JDBC PoolCompac" is set to the wrong query Test "select count(*) from ABILITAZIONI_LMSB" set up for pool "JDBC PoolCompac" failed with exception: "java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
If there is a failure to connect to the database it will not be able to recover.  The Test Connections should be set to Is Valid.

**Comment by mriccell** [comment] 2020-01-31 15:37
Can you ask post the  nfs mount configuration?

It should be something like defaults,_netdev,sync

**Comment by tbarnes-us** [comment] 2021-03-29 21:37
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:37 UTC
