### ISSUE TITLE
Cannot connect to WLST : weblogic stop in k8s pod fails. (FMW 122130)

### ISSUE THREAD

**Issue by meenaal** [oracle/weblogic-kubernetes-operator#1101] opened 2019-06-06 20:29 UTC
Hi Team,

Need help in k8s regarding FMW 122130, applied both the patches p27117282_122130_Generic.zip and p29135930_122130_Generic.zip as mentioned in the readme
Using the available FMW 122130 docker file, I have built and create a new container, where admin-server is in running status, same is accessible from outside the machine as well. Able to deploy the application as well and able to connect from other machines as well.

But in k8s it fails.

I created a yaml for deployment and created a service with type as NodePort and when I tried to connect to an admin-server console outside the machine it is successfully connecting using the node port.

but, when I tried to deploy the application, is not able to connect to the Weblogic server and when i connect to the pod and when I try to stop the weblogic I m getting below error.

Error:
------
[oracle@dom-pdc-two-77df786599-qsq8c bin]$ ./stopWebLogic.sh
Stopping Weblogic Server...

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Connecting to t3://dom-pdc-two-77df786599-qsq8c:9771 with userid  ...

WLST detected that the RuntimeMBeanServer is not enabled. This
might happen if the RuntimeMBeanServer is disabled via the JMXMBean.
Please ensure that this MBeanServer is enabled. Online WLST cannot
function without this MBeanServer.
This Exception occurred at Thu Jun 06 20:13:53 UTC 2019.
java.lang.SecurityException: Anonymous attempt to get to a JNDI resource
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/user_projects/domains/pdc_k8s_1_/shutdown-AdminServer.py", line 3, in ?
  File "<iostream>", line 19, in connect
  File "<iostream>", line 553, in raiseWLSTException
WLSTException: Error occurred while performing connect : "Cannot connect to WLST." : Anonymous attempt to get to a JNDI resource
Use dumpStack() to view the full stacktrace :

Done
Stopping Derby Server...
Derby server stopped.
[oracle@dom-pdc-two-77df786599-qsq8c bin]$

Folder structure and its permission:
---------------------------------------
[oracle@dom-pdc-two-77df786599-qsq8c bin]$ ls -lrt /u01
total 0
drwxr-xr-x 1 root   root    24 Jun  6 18:17 java
drwxr-xr-x 1 root   root    22 Jun  6 18:17 perl
drwxr-xr-x 1 oracle oradba  36 Jun  6 18:22 db_client
drwxr-xr-x 1 oracle oracle 438 Jun  6 19:32 oracle

Oracle is the folder where FMW is installed and user domain is created under user_projects.

I also created below role but didnt work.
kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous

Kindly help me. 

Thanks,
Meena

**Comment by meenaal** [comment] 2019-06-06 20:32
Deployment yaml:
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dom-pdc-two
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dom-pdc-two
    spec:
      # hostNetwork: true
      containers:
      - name: dom-pdc-two
        image: pdcapp:12.0.0.2.0
        command: ["sh"]
        args: ["/u02/container-scripts/installOrStartPdc.sh"]
        ports:
        - containerPort: 9771
          name: pdc-http-port

**Comment by meenaal** [comment] 2019-06-06 20:33
Service yaml 
apiVersion: v1
kind: Service
metadata:
  name: dom-pdc-two
  labels:
    app: dom-pdc-two
spec:
  type: NodePort
  selector:
    app: dom-pdc-two
  ports:
    - name: pdc-http-port
      protocol: TCP
      port: 9771
      targetPort: 9771

**Comment by meenaal** [comment] 2019-06-06 20:35
And also /u01 is root:root permission
but folders under /u01 are oracle:oracle permission

**Comment by rjeberhard** [comment] 2019-06-06 20:36
Hi @meenaal, we just released operator version 2.2.0 today, which is the first operator version to work with FMW infrastructure domains.  Are you using this newest version?  Documentation for working with FMW infrastructure domains is here: https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/fmw-infra/

**Comment by meenaal** [comment] 2019-06-06 20:40
I followed 
https://github.com/oracle/docker-images/tree/master/OracleFMWInfrastructure

**Comment by rjeberhard** [comment] 2019-06-06 20:44
Ah, okay.  The docker-images project has instructions for running in stand-alone Docker containers.  This project is for an operator that assists with running WebLogic in Kubernetes.  I would suggest that in order to run in Kubernetes, you use our operator and the documentation I linked to above.

**Comment by meenaal** [comment] 2019-06-06 20:52
Really appreciate. But my task is to deliver both domain and application related docker and k8s files.
So I need to fix the issue.

**Comment by rjeberhard** [comment] 2019-06-06 21:02
Yes, that's what we have in this project.  The operator is a controller for a custom resource type, Domain, representing a WebLogic domain.  Based on the Domain, the operator creates the necessary Pods and Services to run WebLogic server instances.

I'm not sure how to help on your issue, as we've never tested running the FMW infrastructure images in K8s without the operator.

**Comment by rjeberhard** [comment] 2019-06-06 21:07
Would you consider coming to our public Slack channel?  It might be more efficient to get more people involved in the conversation.  It is here: https://weblogic-slack-inviter.herokuapp.com/

**Comment by meenaal** [comment] 2019-06-06 21:19
Thanks, I m part of CGU unit, as part of private cloud initiative we are asked to deliver the docker files and k8s file for FMW Infra. with AdminServer domain and deploying CGBU application. With Docker, I didn't face any issue, it is working fine, only in k8s t3 is not connecting when I tried to stop the server and I m not able access WebLogic server using localhost as well. I will post the same in the slack as well.

**Comment by rjeberhard** [comment] 2019-06-07 12:16
Closing this as we are discussing the requirements separately and the use case described in the issue is not using the operator.

**Closed by rjeberhard** 2019-06-07 12:16 UTC
