### ISSUE TITLE
Issue in using a WLDF policy rule and script action to call the operator’s REST scale API

### ISSUE THREAD

**Issue by lightistor** [oracle/weblogic-kubernetes-operator#1287] opened 2019-10-02 23:15 UTC
I am trying out WLDF policy+action to run the scalingAction.sh (https://github.com/oracle/weblogic-kubernetes-operator/blob/master/src/scripts/scaling/scalingAction.sh) to trigger a configured domain's (FMW-infra based) scale-up but the script is not executing even when the alert for the threshold is fulfilled for the managed-servers. Is there anyone who tried a similar scenario and was able to execute successfully?

**Few Keypoints**
- domain-home-on-pv (Attached via NFS)
- I am able to trigger the scaling (up and down) via the rest endpoint itself
- weblogic-operator on kube-system namespace (configmap has the respective namespace for the domain)
- scalingAction.sh in $DOMAIN_HOME/bin/scripts for r/w/x is 777, ownership of the file belongs to "oracle" user for which the domain home was created-configured.

**Diagnostic Module config** (k8sScalingTestPolicy is the enabled policy, k8sScaleUpPolicy created as per the [Automatic Scaling of WebLogic Clusters on Kubernetes](https://blogs.oracle.com/weblogicserver/automatic-scaling-of-weblogic-clusters-on-kubernetes-v2) is disabled as it was only valid for a dynamic cluster):
`<?xml version='1.0' encoding='UTF-8'?>
<wldf-resource xmlns="http://xmlns.oracle.com/weblogic/weblogic-diagnostics" xmlns:sec="http://xmlns.oracle.com/weblogic/security" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wls="http://xmlns.oracle.com/weblogic/security/wls" xsi:schemaLocation="http://xmlns.oracle.com/weblogic/weblogic-diagnostics http://xmlns.oracle.com/weblogic/weblogic-diagnostics/2.0/weblogic-diagnostics.xsd">
  <name>Module-0</name>
  <watch-notification>
    <watch>
      <name>k8sScaleUpPolicy</name>
      <enabled>false</enabled>
      <rule-type>Harvester</rule-type>
      <rule-expression>wls:ClusterGenericMetricRule("DockerCluster", "com.bea:Type=WebAppComponentRuntime,ApplicationRuntime=TestWebApp,*", "OpenSessionsCurrentCount","&amp;gt;=",0.01,5,"1 seconds","10 seconds")</rule-expression>
      <expression-language>EL</expression-language>
      <alarm-type>AutomaticReset</alarm-type>
      <schedule>
        <minute>*</minute>
        <second>*/15</second>
      </schedule>
      <alarm-reset-period>600000</alarm-reset-period>
      <notification>scriptK8SWLOPScaleUpForK8SScaleUpPolicy</notification>
    </watch>
    <watch>
      <name>k8sScalingTestPolicy</name>
      <enabled>true</enabled>
      <rule-type>Harvester</rule-type>
      <rule-expression>wls:ServerHighProcessCpuLoadAverage("30 seconds","10 minutes",0.1)</rule-expression>
      <expression-language>EL</expression-language>
      <alarm-type>AutomaticReset</alarm-type>
      <schedule>
        <minute>*</minute>
        <second>*/1</second>
      </schedule>
      <alarm-reset-period>600000</alarm-reset-period>
      <notification>scriptK8SWLOPScaleUpForK8SScaleUpPolicy</notification>
    </watch>
    <script-action>
      <name>scriptK8SWLOPScaleUpForK8SScaleUpPolicy</name>
      <enabled>true</enabled>
      <timeout>0</timeout>
      <working-directory>/home/oracle/shared/k8s-wl/osb0/domains/osb0/bin/scripts</working-directory>
      <path-to-script>/home/oracle/shared/k8s-wl/osb0/domains/osb0/bin/scripts/scalingAction.sh</path-to-script>
      <environment>INTERNAL_OPERATOR_CERT=BLOB</environment>
      <parameter>--action=scaleUp
--domain_uid=osb0
--cluster_name=cluster-0
--operator_namespace=kube-system
--operator_service_account=default
--operator_service_name=internal-weblogic-operator-svc
--kubernetes_master=https://10.132.239.175:6443
--scaling_size=1
--access_token=BLOB</parameter>
    </script-action>
    <script-action>
      <name>scriptK8SWLOPScaleDownForK8SScaleUpPolicy</name>
      <enabled>false</enabled>
      <timeout>0</timeout>
      <working-directory>/home/oracle/shared/k8s-wl/osb0/domains/osb0/bin/scripts</working-directory>
      <path-to-script>/home/oracle/shared/k8s-wl/osb0/domains/osb0/bin/scripts/scalingAction.sh</path-to-script>
      <environment>INTERNAL_OPERATOR_CERT=BLOB</environment>
      <parameter>--action=scaleDown
--domain_uid=osb0
--cluster_name=cluster-0
--operator_namespace=kube-system
--operator_service_account=default
--operator_service_name=internal-weblogic-operator-svc
--kubernetes_master=https://10.132.239.175:6443
--scaling_size=1
--access_token=BLOB</parameter>
    </script-action>
  </watch-notification>
</wldf-resource>
`

**Additional Details**
Another thing to note, as per the suggestion in [Automatic Scaling of WebLogic Clusters on Kubernetes](https://blogs.oracle.com/weblogicserver/automatic-scaling-of-weblogic-clusters-on-kubernetes-v2) I had set the target to admin. However, doing so would not yield any entry for the policy "notice" in the logs. When I switched the target to cluster, I began to see the notice-level log entry coming up in the managed-server logs such as:
`<Oct 2, 2019 4:30:23,147 PM GMT> <Notice> <Diagnostics> <BEA-320068> <Watch "k8sScalingTestPolicy" in module "Module-0" with severity "Notice" on server "osb_server1" has triggered at Oct 2, 2019 4:30:23 PM GMT. Notification details:
WatchRuleType: Harvester
WatchRule: wls:ServerHighProcessCpuLoadAverage("30 seconds","10 minutes",0.05)
WatchData: java.lang:type=OperatingSystem//ProcessCpuLoad = [0.018714156353757925, 0.025621703089675964, 0.05514705882352941, 0.14285714285714285, 0.0947176684881603, 0.015455950540958269, 0.03686150605581885, 0.026194144838212637, 0.019310344827586208, 0.017173051519154558, 0.013963480128893663, 0.018565400843881856, 0.06909090909090909, 0.034782608695652174, 0.19948685054522128, 0.04993053143452588, 0.018655433287482807, 0.02956596476149549, 0.0967208837087936, 0.3807482342781359]
WatchAlarmType: AutomaticReset
WatchAlarmResetPeriod: 600000`

And one more thing, although this was not the case for managed-server-1, for managed-server-2; the pod's log had the following entry:
`<Oct 2, 2019 2:15:59,990 PM GMT> <Warning> <oracle.osb.statistics.statistics> <OSB-473012> <Timer (Checkpoint) has been triggered with a tick (5,176) that is less than or equal to the last tick that was received (5,176). This could happen in a cluster due to clock synchronization with the timer authority. The current trigger will be ignored, and operation will be skipped.>after the diagnostic module policy notice's entry (after 34 minutes).`

**Comment by lennyphan** [comment] 2019-10-09 18:42
To help debug how WLDF is evaluating the metrics and rules, you can run the managed server at which the policy is targeted (for example Admin Server for Cluster-scoped smart rules) with the following system properties for debug output of the WLDF component:
-Dweblogic.StdoutDebugEnabled=true -Dweblogic.log.LogSeverity=Debug -Dweblogic.log.LoggerSeverity=Debug  -Dweblogic.debug.DebugDiagnosticWatch=true -Dweblogic.debug.DebugDiagnosticWatcDebugDiagnosticsExpressionMetrics=true 
-Dweblogic.debug.DebugDiagnosticsExpressionPoller=true

The WLDF debug output will provide information on what metrics are being collected and if/when the associated action is invoked.

**Comment by tbarnes-us** [comment] 2021-03-29 21:40
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:40 UTC
