### ISSUE TITLE
Support domain on PV using directory path root in image (/u01)

### ISSUE THREAD

**Issue by anilarora** [oracle/weblogic-kubernetes-operator#1244] opened 2019-09-06 16:00 UTC
The operator is not able to introspect the domain in the "domain on PV" use case unless the domain home is located under /shared.  I tried setting the following in the domain resource

  domainHome: "/u01/config/domains/domain3"
  domainHomeInImage: false

where /u01/config is the volume mount point.

**Comment by tbarnes-us** [comment] 2019-09-06 16:50
I wonder if the issue has something to do with choosing '/u01/config' as the mount path, since the '/u01' directory typically already exists within the image.

Is there a mount error reported in a kubectl describe of the introspector job? This would indicate that kubernetes wasn't able to mount the specified location in the first place.  If not, what error is reported in the job's log? If so, can you retry with a directory with a root path that doesn't overlap a pre-existing directory?

**Comment by anilarora** [comment] 2019-09-06 20:03
Interesting...If I change the mount to /testconfig, it seems to go through.

**Comment by anilarora** [comment] 2019-09-06 20:19
When I use /u01/config as the mount point, I don't see the introspector job created.  I see this in the weblogic-operator logs.

{"timestamp":"09-06-2019T20:18:00.546+0000","thread":29,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.DomainProcessorImpl","method":"dispatchDomainWatch","timeInMillis":1567801080546,"message":"Watch event triggered for WebLogic Domain with UID: domain3","exception":"","code":"","headers":{},"body":""}
{"timestamp":"09-06-2019T20:18:00.547+0000","thread":29,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.DomainProcessorImpl","method":"internalMakeRightDomainPresence","timeInMillis":1567801080547,"message":"Creating or updating Kubernetes presence for WebLogic Domain with UID: domain3","exception":"","code":"","headers":{},"body":""}

**Comment by tbarnes-us** [comment] 2019-09-06 23:09
Hmm. Are you sure the job wasn't created? I've yet to see a case where the Operator doesn't at least try to create the job. Usually a failed mount reports an error in the 'kubectl describe' of the job (or maybe it's the job's pod?).  

Regardless, it looks like the issue is solved. PV/C mount points that overlap an image's burned-in directory tree are apparently verboten in kubernetes.  (We learn something new everyday.)  If you agree, can you close the Issue?

Side note:  The next version of the operator is slated to report job mount issues in the domain resource status (which can be checked via kubectl describe domain my-domain).  It may also log in the operator.  So hopefully the next time a mount issue causes trouble it'll be easier to diagnose.  

@russgold FYI

**Comment by anilarora** [comment] 2019-09-07 00:34
I don't know if the job was created but I don't see it when I do a "kubectl get pods -n <namespace>" so if it's getting deleted in some loop somewhere...

BTW, I use the same volumeMount mapping in my job batch resource that creates the domain, so it should be technically possible.

Let's keep this open because it still feels like an issue.  We have been using /u01/config for our domain storage and want to keep that so we are consistent across our various offerings that use that as the folder structure.

**Comment by tbarnes-us** [comment] 2019-09-07 04:02
If the mount is failing, it could be the reason you can't see the pod.  A kubectl describe of the job might be instructive.  "kubectl get jobs", then "kubectl describe job the-job".

I'm not sure what can be done to directly work around the issue.  This looks like a limitation of docker/kubernetes - not the operator.  Off the top of my head, all I can think of is modifying the job/pod start scripts to `ln` link your /u01/config directory to the actual mount location - but there is risk there - I don't know how tolerant WLS is about using linked directories.

**Comment by tbarnes-us** [comment] 2019-09-07 04:22
Hmm, I might be assuming to much that this is a docker/kubernetes limitation.   I wonder if this is simply a permission issue. 

It looks like u01 is owned by oracle:  "drwxr-xr-x   1 oracle oracle 4096 Sep  5 15:01 u01" is owned by oracle.   Where as /shared in my sample is owned by root, which indicates to me that a pv/c creates a mount using root by default even if the pod is running as the oracle user.  So maybe either the /u01 directory permission needs to be widened when the image is created, or, likely easier: the pv/c mount needs to be instructed to create the mount directory as the oracle user.  I recall @TheFrogPad saying that there's a way to do the latter.

**Comment by tbarnes-us** [comment] 2019-09-10 16:45
Issue #1228 may be related.

**Comment by tbarnes-us** [comment] 2021-03-29 21:50
I'm assuming the issue was long ago resolved by now, but feel free to re-open if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:50 UTC
