### ISSUE TITLE
Coherent naming convention for SOA and OSB managed servers

### ISSUE THREAD

**Issue by GerthH** [oracle/weblogic-kubernetes-operator#1622] opened 2020-05-05 11:35 UTC
WKO uses in create-domain-inputs.yaml

a default static managedServerNameBase "osb_server" when it creates the the OSB managed servers
a changable managedServerNameBase "soa_server" when it creates the the SOA managed servers
if eg type soaessosb has been chosen.
See

# Base string used to generate managed server names
managedServerNameBase: soa_server
# Port number for each managed server
managedServerPort: 8001

This should be replaced by eg
osbManagedServerNameBase: osb_server
osbManagedServerPort: 9001
soaManagedServerNameBase: soa_server
soaManagedServerPort: 8001
to let users be able to maintain a coherent naming convention for managed servers  created by one declaration and generation from WKO for OSB and SOA clusters.

A sample of what could happen is if I choose to set
soaManagedServerNameBase: soa1_server
soaManagedServerPort: 8001
WKO would generate:
pod/soainfra-osb-server1
pod/soainfra-osb-server2
pod/soainfra-soa1-server1
pod/soainfra-soa1-server2
not giving me the opportunity to maintain a coherent naming convention for osb to match soa; ie ...osb1....

**Comment by jshum2479** [comment] 2020-05-05 18:50
Similar comment as 1621, you are asking options to configure the base server name for each cluster, when the domainType is set as soaosb?

**Comment by GerthH** [comment] 2020-05-05 19:24
Yes, for any of the domain types:
soa: Deploys a SOA domain
osb: Deploys an OSB (Oracle Service Bus) domain
soaess: Deploys a SOA domain with Enterprise Scheduler (ESS)
soaosb: Deploys a domain with SOA and OSB
soaessosb: Deploys a domain with SOA, OSB, and ESS

Especially for soaosb and soaessosb since two clusters, each with their on set of managed servers are created.

**Comment by tbarnes-us** [comment] 2021-03-29 21:27
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:27 UTC
Labels: SOA
