### ISSUE TITLE
Coherent naming convention for SOA and OSB clusters

### ISSUE THREAD

**Issue by GerthH** [oracle/weblogic-kubernetes-operator#1621] opened 2020-05-05 11:27 UTC
WKO uses in create-domain-inputs.yaml
-  a default static suffix "osb_cluster" when it creates the the OSB cluster
-  a changable suffix "soa_cluster" when it creates the the SOA cluster
if eg type soaessosb has been chosen.

See 
# Cluster name
clusterName: soa-cluster

This should be replaced by eg 
osbClusterName: osb_cluster
soaClusterName: soa_cluster
to let users be able to maintain a coherent naming convention for cluster created by one declaration and generation from WKO.

A sample of what could happen is if I choose to set
domainUID: soainfra
clusterName: soa1_cluster
WKO would generate:
soainfra-osb-cluster 
soainfra-soa1-cluster
not giving me the opportunity to maintain a naming convention for osb to match soa; ie ...osb1....

**Comment by jshum2479** [comment] 2020-05-05 18:48
I can only deduce you are requesting the ability to configure the osb and soa cluster name when the domainType is set to soaosb?

**Comment by GerthH** [comment] 2020-05-05 19:23
Yes, for any of the domain types:
soa: Deploys a SOA domain
osb: Deploys an OSB (Oracle Service Bus) domain
soaess: Deploys a SOA domain with Enterprise Scheduler (ESS)
soaosb: Deploys a domain with SOA and OSB
soaessosb: Deploys a domain with SOA, OSB, and ESS

Especially for soaosb and soaessosb since two clusters are created for these.

**Comment by tbarnes-us** [comment] 2021-03-29 21:31
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

**Closed by tbarnes-us** 2021-03-29 21:31 UTC
Labels: SOA
