### ISSUE TITLE
repository docker.io/my-domain1-image not found: does not exist or no pull access

### ISSUE THREAD

**Issue by fabras78** [oracle/weblogic-kubernetes-operator#1673] opened 2020-05-22 15:25 UTC
Hello,

I'm using minishift minishift v1.34.1+c2ff9cb 

I stucked on this step 
$ oc apply -f domain.yaml

in minishift events I found this error:

Failed to pull image "my-domain1-image:1.0": rpc error: code = Unknown desc = repository docker.io/my-domain1-image not found: does not exist or no pull access

but if I do 
$ docker images | grep my-
my-domain1-image                      1.0                 a9bff6743fe3        40 minutes ago      2.08GB

Why minishift can't pull from local repository?

thx

**Comment by markxnelson** [comment] 2020-05-22 15:29
We do not support minishift. I think that it runs the cluster in a vm, and do you probably need to run some command to load the image into that vm, or copy it into the local minishift registry.

**Comment by fabras78** [comment] 2020-05-25 09:55
exactly!
with hyperV you have a VM with docker so you need to export on filesystem the image using sequence:
1) build image on local docker with quickBuild.sh
2) export the image with command:  docker -o my-domain1-image 1.0 my-domain
3) login on hyperV docker using docker login 
4) docker -i my-domain my-domain1-image 1.0

**Comment by tbarnes-us** [comment] 2020-06-08 20:59
Closing because it looks like the problem is resolved.  Feel free to re-open if this isn't true.

**Closed by tbarnes-us** 2020-06-08 20:59 UTC
