### ISSUE TITLE
External NodePort services for managed servers

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#1110] opened 2019-06-12 22:23 UTC
The requirement is to make individual managed servers externally visible using NodePort-type Services, similarly to what is currently offered for the administration server.

The current support for the administration server includes:
- Operator always creates a ClusterIP-type Service for the administration server that includes ports for all of the various "default" channels and all network access points
- The ports on this internal Service match the ports on the Pod
- Customer can specify Domain resource content under spec.adminServer.adminService that controls the optional creation of a second, "external" Service with type NodePort.
- This second NodePort-type Service  includes a selected set of ports depending on what the customer has configured in spec.adminServer.adminService.channels

The current support for managed server instances includes:
- Identical support for a ClusterIP-type Service with ports matching those on the Pod
- No support for an external, NodePort-type Service
- No Domain resource schema analogous to spec.adminServer.adminService

We must define Domain resource schema and matching implementation such that is possible to create external services for each managed server instance, e.g. spec.managedServers[*].externalService.

However, we believe this will not be sufficiently usable.  The problem is that what is implied by the above will result in lots of duplicate content (since all of the managed servers in a cluster will want to expose the same set of channels) and because customers will be forced to configure the NodePort values for every managed server instance.  Therefore, we believe that this functionality requires the ability to specify configuration of a range or pattern for NodePort values of the managed server members of a cluster.  This configuration would be at the cluster-level.

This functionality is complete when:
- Changes to schema are reviewed and agreed
- Implementation including unit-tests
- User documentation updated

**Comment by bryantidd** [comment] 2019-06-13 18:57
Could this be achieved with a boolean at the cluster level for allowing a cluster IP on managed servers, instead of a service with an cluster IP set to none? Then access could be available within the cluster, or  added to an ingress.

**Comment by bryantidd** [comment] 2019-06-13 19:13
In other words a second set of managed server instance services with Cluster IP: xx.xx.xx.xx

**Comment by tbarnes-us** [comment] 2021-03-29 22:13
@rjeberhard @mriccell Is there an internal JIRA tracking this? If, so please add it here.

**Comment by tbarnes-us** [comment] 2021-03-29 22:18
I'm assuming the issue is resolved by now: from what I can tell, it may have been left open by Ryan as a reminder to enhance the documentation.  Feel free to re-open the issue if I'm incorrect.

@rjeberhard FYI

**Comment by tbarnes-us** [comment] 2021-03-29 22:19
Oops, that last comment, and the 'close' was in error (they were meant for a different Issue).  Re-opening.

**Closed** 2022-04-27 18:20 UTC
Labels: enhancement
