### ISSUE TITLE
Error: parse error at (weblogic-operator/templates/_operator-secret.tpl:12): function "lookup" not defined

### ISSUE THREAD

**Issue by streethawkz** [oracle/weblogic-kubernetes-operator#1960] opened 2020-09-30 11:33 UTC
git clone https://github.com/oracle/weblogic-kubernetes-operator.git 

and then if try to install wls-operator using helm :

@cloudshell:weblogic-kubernetes-operator (ap-hyderabad-1)$ helm install sample-weblogic-operator \
>   kubernetes/charts/weblogic-operator \
>   --namespace sample-weblogic-operator-ns \
>   --set image=oracle/weblogic-kubernetes-operator:3.0.2 \
>   --set serviceAccount=sample-weblogic-operator-sa \
>   --set "domainNamespaces={}"

I get this error error : 

Error: parse error at (weblogic-operator/templates/_operator-secret.tpl:12): function "lookup" not defined

--

If clone older version :  

git clone https://github.com/oracle/weblogic-kubernetes-operator.git -b v3.0.0

Then the wls-operator gets created successfully.

**Comment by streethawkz** [comment] 2020-09-30 11:45
I see this issue on version 3.0.2 and 3.0.1.

But it works fine on version 3.0.0 : 

git clone https://github.com/oracle/weblogic-kubernetes-operator.git -b v3.0.0
Cloning into 'weblogic-kubernetes-operator'...
remote: Enumerating objects: 943, done.
remote: Counting objects: 100% (943/943), done.
remote: Compressing objects: 100% (548/548), done.
remote: Total 164455 (delta 406), reused 633 (delta 231), pack-reused 163512
Receiving objects: 100% (164455/164455), 114.47 MiB | 6.64 MiB/s, done.
Resolving deltas: 100% (96027/96027), done.
Note: checking out 'a14b76777ccd1e039b64ea2992d8a22da05f8e3d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files: 100% (10812/10812), done.
@cloudshell:~ (ap-hyderabad-1)$ cd weblogic-kubernetes-operator/
@cloudshell:weblogic-kubernetes-operator (ap-hyderabad-1)$ helm install sample-weblogic-operator \
>   kubernetes/charts/weblogic-operator \
>   --namespace sample-weblogic-operator-ns \
>   --set image=oracle/weblogic-kubernetes-operator \
>   --set serviceAccount=sample-weblogic-operator-sa \
>   --set "domainNamespaces={}"
NAME: sample-weblogic-operator
LAST DEPLOYED: Wed Sep 30 11:40:45 2020
NAMESPACE: sample-weblogic-operator-ns
STATUS: deployed
REVISION: 1
TEST SUITE: None

**Comment by rjeberhard** [comment] 2020-09-30 13:04
In order to fix an issue in the Helm chart, we had to use a feature introduced in Helm 3.1. I will ask the Cloud Shell team when they will update the default Helm version.

**Comment by tbarnes-us** [comment] 2021-03-29 20:38
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 20:38 UTC
