### ISSUE TITLE
Problem with Server Start Arguments.

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-kubernetes-operator#106] opened 2018-02-20 17:31 UTC
Hello,
Via console I tried to change under `Environments -> Servers -> managed-server1(2) -> Configuration tab -> Server Start subtab` the `Arguments` with something like this : 
```java
-Dfile.encoding=utf8 -Djava.net.preferIPv4Stack=true -DentityExpansionLimit=10000 -Xmx512m
```
I killed the managed server pod and let the operator restart it.
It seems that the managed server is started without these parameters even if these values are saved in the config.xml.

For example if I checked on the container with : 
```bash
cat /proc/`jps | grep Server | awk '{print $1}'`/cmdline
```
This comand print the start command of the server and the parameters are not there>
They should be also in the `startup.properties` under the nodemanager directory.(in the today call I said nodemanager.properties, sorry i confused the names).

**Comment by tbarnes-us** [comment] 2018-02-21 21:54
Hi, 

Thanks you for filing this Issue.   I don't think the operator currently supports setting WebLogic JVM command line arguments via the WebLogic console, although I can certainly see how that might be convenient I'm not sure whether it'd be straight forward to implement.    Do you think this should be a high priority?     

Alternatively, it should be possible to set WebLogic JVM command line args via the JAVA_OPTIONS/USER_MEM_ARGS env vars in your domain custom resource yaml.    Here's a yaml snippet:

```
  serverStartup:
  # desiredState legal values are "RUNNING" or "ADMIN"
  # "RUNNING" means the listed server will be started up to "RUNNING" mode
  # "ADMIN" means the listed server will be start up to "ADMIN" mode
  - desiredState: "RUNNING"
    # the name of the server to apply these rules to
    serverName: "admin-server"
    # an (optional) list of environment variable to be set on the server
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
  # clusterStartup has the same structure as serverStartup, but it allows you to specify the name
  # of a cluster instead of an individual server.  If you use this entry, then the rules will be
  # applied to ALL servers that are members of the named clusters.
  clusterStartup:
  - desiredState: "RUNNING"
    clusterName: "cluster-1"
    replicas: 2
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
```

If you resubmit the domain yaml I'm fairly sure the operator is expected to detect the change and restart the pod(s).  

Also, if you're using the 'create-domain-job' helper script to create your domain yaml, you can specify an initial value for JAVA_OPTIONS using the 'javaOptions' tag via the create-domain-job-input yaml that feeds options into the helper script.

Hope this helps!

**Comment by tbarnes-us** [comment] 2018-02-21 22:08
Oops!   I was just told that the JAVA_OPTIONS/javaOptions settings I just described only currently works for managed servers -- there's some sort of known issue with admin servers.

**Comment by antonionappi88** [comment] 2018-02-22 09:54
Hi @tbarnes-us, It has not high priority but it was a way to understand how much persistent is the environment! For the moment if I need I'll try with the JAVA_OPTIONS in the yaml file ( at least for the managed). Thank you!

**Comment by tbarnes-us** [comment] 2018-02-22 16:31
Hi @antonionappi88 - FYI - The changes you made on the console actually are persisted to the WL config.xml, but are ignored.    The problem is that the JVM arguments in particular are handled/overridden by a special path through the system that's unique to the kubernetes weblogic operator: the operator needs to take over the WL lifecycle to some degree and its logic currently doesn't check the config.xml setting.    You should find it possible to modify pretty much all other config.xml (of course you'll still need to make sure that network settings, etc, align with the corresponding kubernetes domain yaml settings).

**Comment by doxiao** [comment] 2018-02-28 20:23
FYI - the environment properties JAVA_OPTIONS and USER_MEM_ARGS configured via the admin server's serverStartup take effect now.  What has been suggested above by tbarnes-us should work if you pull the latest master.

**Comment by rjeberhard** [comment] 2018-03-01 20:34
Proposal: We will support config.xml options for managed servers.  We presently won't be able to support these options for the administration server, but likely will be able to when we migrate to the WebLogic domain tooling.

We will also maintain the serverStartup.env configuration in the domain spec.  Therefore, we need to consider precedence.  I'm leaning toward the default being that the values in the domain spec having the highest precedence and overriding the values in config.xml.  We should also support having being able to configure that config.xml values override and, perhaps, that they two sets of options are merged.

**Comment by antonionappi88** [comment] 2018-03-02 08:34
I see. Thank you all for the help!

**Closed** 2018-03-21 15:17 UTC
Labels: customer reported, enhancement
