### ISSUE TITLE
create-domain.sh gives [ERROR] Create domain sample-domain1 failed.

### ISSUE THREAD

**Issue by creativefre** [oracle/weblogic-kubernetes-operator#1028] opened 2019-04-12 08:52 UTC
Hello, I get the following error when I run the create-domain.sh

Kubernetes is setup correctly and the images are pulled.
I'm following the QUICK START guide from the documentation. Every command before this executed successfully.

When I try to create the domain with the following command,

`sudo ./create-domain.sh -i my-inputs.yaml -o /home/oracle/WERK -u weblogic -p welcome1 -e`

I get the following output.
```bash
oracle@lnx-stage01:~/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image$ sudo ./create-domain.sh -i my-inputs.yaml -o /home/oracle/WERK -u weblogic -p welcome1 -e
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export adminPort="7001"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="3"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export productionModeEnabled="true"
export imagePullPolicy="IfNotPresent"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="sample-domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="store/oracle/weblogic:12.2.1.3"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"

Cloning into './docker-images'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 10023 (delta 24), reused 31 (delta 13), pack-reused 9966
Receiving objects: 100% (10023/10023), 8.88 MiB | 10.55 MiB/s, done.
Resolving deltas: 100% (5819/5819), done.
Generating /home/oracle/WERK/weblogic-domains/sample-domain1/domain.properties
Generating /home/oracle/WERK/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
A properties file with variable definitions should be supplied.
[ERROR] Create domain sample-domain1 failed.
```
I can't seem to figure out what the problem is.
This is the content of my-inputs.yaml
```yaml
# Copyright 2018, 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

# The version of this inputs file.  Do not modify.
version: create-weblogic-sample-domain-inputs-v1

# Port number for admin server
adminPort: 7001

# Name of the Admin Server
adminServerName: admin-server

# Unique ID identifying a domain.
# This ID must not contain an underscope ("_"), and must be lowercase and unique across all domains
# in a Kubernetes cluster.
domainUID: sample-domain1

# Determines which WebLogic Servers the operator will start up
# Legal values are "NEVER", "IF_NEEDED", or "ADMIN_ONLY"
serverStartPolicy: IF_NEEDED

# Cluster name
clusterName: cluster-1

# Number of managed servers to generate for the domain
configuredManagedServerCount: 5

# Number of managed servers to initially start for the domain
initialManagedServerReplicas: 3

# Base string used to generate managed server names
managedServerNameBase: managed-server

# Port number for each managed server
managedServerPort: 8001

# Boolean indicating if production mode is enabled for the domain
productionModeEnabled: true

# WebLogic Server Docker image that the operator uses to start the domain.
#
# The create domain scripts generate a WebLogic Server Docker image with a domain home in it.
# By default, the scripts tag the generated WebLogic server Docker image as either
# `domain-home-in-image` or `domain-home-in-image-wdt` based on the `domainHomeImageBuildPath`
# property, and use it to set the `image` element in the generated domain YAML file.
#
# If this property is set, the create domain scripts will use the value specified, instead of the
# default value, to tag the generated image and set the `image` in the domain YAML file.
#
# A unique value is required for each domain that is created using the scripts.
#
# If you are running the sample scripts from a machine that is remote to the Kubernetes cluster where
# the domain is going to be running, you need to set this property to the image name that is intended
# to be used in a registry local to that Kubernetes cluster. You also need to push the `image` to
# that registry before starting the domain using the `kubectl create -f` or `kubectl apply -f` command.
# See README.md for more help.
#image:

# Image pull policy
# Legal values are "IfNotPresent", "Always", or "Never"
imagePullPolicy: IfNotPresent

# Name of the Kubernetes secret to access the Docker Store to pull the WebLogic Server Docker image
# The presence of the secret will be validated when this parameter is enabled.
#imagePullSecretName:

# Name of the Kubernetes secret for the Admin Server's username and password
# The name must be lowercase.
# If not specified, the value is derived from the domainUID as <domainUID>-weblogic-credentials
weblogicCredentialsSecretName: sample-domain1-weblogic-credentials

# Whether to include server .out to the pod's stdout.
# The default is true.
includeServerOutInPodLog: true

# Specifies whether the log home is stored on the persistent volume.
# If set to true, then you must specify the 'logHome', 'persistentVolumeClaimName'
# and 'domainPVMountPath' properties.
# The default is false.
logHomeOnPV: false

# The in-pod location for domain log, server logs, server out, and node manager log files
# If not specified, the value is derived from the domainUID as /shared/logs/<domainUID>
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
logHome: /shared/logs/domain1

# Port for the T3Channel of the NetworkAccessPoint
t3ChannelPort: 30012

# Public address for T3Channel of the NetworkAccessPoint.  This value should be set to the
# kubernetes server address, which you can get by running "kubectl cluster-info".  If this
# value is not set to that address, WLST will not be able to connect from outside the
# kubernetes cluster.
#t3PublicAddress:

# Boolean to indicate if the channel should be exposed as a service
exposeAdminT3Channel: false

# NodePort to expose for the admin server
adminNodePort: 30701

# Boolean to indicate if the adminNodePort will be exposed
exposeAdminNodePort: false

# Name of the domain namespace
namespace: sample-domain1-ns

# Java Option for WebLogic Server
javaOptions: -Dweblogic.StdoutDebugEnabled=false

# Name of the persistent volume claim
# If not specified, the value is derived from the domainUID as <domainUID>-weblogic-sample-pvc
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
persistentVolumeClaimName: sample-domain1-weblogic-sample-pvc

# Mount path of the domain persistent volume.
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
domainPVMountPath: /shared

# Base WebLogic binary image used to build the WebLogic domain image
# The operator requires WebLogic Server 12.2.1.3.0 with patch 29135930 applied.
# The existing WebLogic Docker image, `store/oracle/weblogic:12.2.1.3`, was updated on January 17, 2019,
# and has all the necessary patches applied; a `docker pull` is required if you already have this image.
# Refer to [WebLogic Docker images](../../../../../site/weblogic-docker-images.md) for details on how
# to obtain or create the image.
# See README.md for more help.
domainHomeImageBase: store/oracle/weblogic:12.2.1.3

# Location of the WebLogic "domain home in image" Docker image sample in the
# `https://github.com/oracle/docker-images.git` project.
# If not specified, use "./docker-images/OracleWebLogic/samples/12213-domain-home-in-image".
# Another possible value is "./docker-images/OracleWebLogic/samples/12213-domain-home-in-image-wdt",
# which uses WDT, instead of WLST, to generate the domain configuration.
domainHomeImageBuildPath: ./docker-images/OracleWebLogic/samples/12213-domain-home-in-image
```

Any suggestions on how to solve this would be a great help!

**Comment by simon-meng-cn** [comment] 2019-04-12 09:53
Check you environment,  whether the file /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/docker-build/domain.properties  exists?

**Comment by simon-meng-cn** [comment] 2019-04-12 09:56
If the property file does not exist, copy /home/oracle/WERK/weblogic-domains/sample-domain1/domain.properties to that location. Then execute the create domain script with -k option

sudo ./create-domain.sh -i my-inputs.yaml -o /home/oracle/WERK -u weblogic -p welcome1 -e -k

**Comment by creativefre** [comment] 2019-04-12 10:22
Thanks for the response,
The error is stil there.

I copied the domain.properties (the docker-build dir did not exist) to /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/docker-build/ 
And executed the given command
```bash
oracle@lnx-stage01:~/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image$ sudo ./create-domain.sh -i my-inputs.yaml -o /home/oracle/WERK -u weblogic -p welcome1 -e -k
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export adminPort="7001"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="3"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export productionModeEnabled="true"
export imagePullPolicy="IfNotPresent"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="sample-domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="store/oracle/weblogic:12.2.1.3"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"

Generating /home/oracle/WERK/weblogic-domains/sample-domain1/domain.properties
Generating /home/oracle/WERK/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
A properties file with variable definitions should be supplied.
[ERROR] Create domain sample-domain1 failed.
```

**Comment by simon-meng-cn** [comment] 2019-04-12 11:56
I ran the sample recently, it worked fine. The command I used is:
./create-domain.sh -i my-inputs.yaml -o my-output -u weblogic -p welcome1
my-output is relative path. It is subdir of current dir. Another difference is not runas root.

Could you try my way to diagnose the issue? I suspect the one of the difference caused the issue.

**Comment by creativefre** [comment] 2019-04-12 12:17
Still the same error.
I'm running it on ubuntu 18.04 LTS desktop

```bash
oracle@lnx-stage01:~/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image$ ./create-domain.sh -i my-inputs.yaml -o my-output -u weblogic -p welcome1
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export adminPort="7001"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="3"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export productionModeEnabled="true"
export imagePullPolicy="IfNotPresent"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="sample-domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="store/oracle/weblogic:12.2.1.3"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"

Cloning into './docker-images'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 10023 (delta 24), reused 31 (delta 13), pack-reused 9966
Receiving objects: 100% (10023/10023), 8.88 MiB | 11.73 MiB/s, done.
Resolving deltas: 100% (5819/5819), done.
Generating my-output/weblogic-domains/sample-domain1/domain.properties
Generating my-output/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
A properties file with variable definitions should be supplied.
[ERROR] Create domain sample-domain1 failed.
```

**Comment by simon-meng-cn** [comment] 2019-04-12 12:36
Which operator code branch that you used? I want use the same code to create domain on my machine.

**Comment by creativefre** [comment] 2019-04-12 12:39
I used the master branch.

**Comment by simon-meng-cn** [comment] 2019-04-12 13:06
I created the domain successfully followed by the quick start. Following is the output:

bash-4.2$ pwd
/scratch/simeng/weblogic-kubernetes-operator
bash-4.2$ kubernetes/samples/scripts/create-weblogic-domain-credentials/create-weblogic-credentials.sh \
>   -u weblogic -p welcome1 -n sample-domain1-ns -d sample-domain1
secret "sample-domain1-weblogic-credentials" created
secret "sample-domain1-weblogic-credentials" labeled
The secret sample-domain1-weblogic-credentials has been successfully created in the sample-domain1-ns namespace.
bash-4.2$ cd kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image
bash-4.2$ ls
create-domain-inputs.yaml  create-domain.sh  properties-template.properties  README.md
bash-4.2$ cp create-domain-inputs.yaml my-inputs.yaml
bash-4.2$ vim my-inputs.yaml 
bash-4.2$ ./create-domain.sh -i my-inputs.yaml -o /some/output/directory -u weblogic -p welcome1^C
bash-4.2$ ./create-domain.sh -i my-inputs.yaml -o my-output -u weblogic -p welcome1
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export adminPort="7001"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="2"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export productionModeEnabled="true"
export imagePullPolicy="IfNotPresent"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="store/oracle/weblogic:12.2.1.3"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"

Cloning into './docker-images'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 10023 (delta 24), reused 31 (delta 13), pack-reused 9966
Receiving objects: 100% (10023/10023), 8.88 MiB | 5.35 MiB/s, done.
Resolving deltas: 100% (5809/5809), done.
Generating my-output/weblogic-domains/sample-domain1/domain.properties
Generating my-output/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /scratch/simeng/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
Export environment variables from the /scratch/simeng/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-build/domain.properties properties file
CUSTOM_DOMAIN_NAME=sample-domain1
CUSTOM_ADMIN_NAME=admin-server
CUSTOM_ADMIN_HOST=wlsadmin
CUSTOM_ADMIN_PORT=7001
CUSTOM_MANAGED_SERVER_PORT=8001
CUSTOM_DEBUG_PORT=8453
Set the image tag name to domain-home-in-image:12.2.1.3
BUILD_ARG= --build-arg CUSTOM_DOMAIN_NAME=sample-domain1 --build-arg CUSTOM_ADMIN_NAME=admin-server --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_PORT=7001 --build-arg CUSTOM_MANAGED_SERVER_PORT=8001 --build-arg CUSTOM_DEBUG_PORT=8453
Sending build context to Docker daemon 44.54 kB
Step 1/17 : FROM store/oracle/weblogic:12.2.1.3
 ---> d58f0d158db5
Step 2/17 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Running in 3e3e293970a7
 ---> 12fad4286e4b
Removing intermediate container 3e3e293970a7
Step 3/17 : ARG CUSTOM_DOMAIN_NAME="${CUSTOM_DOMAIN_NAME:-domain1}"
 ---> Running in d9655f709fca
 ---> 8aed84508710
Removing intermediate container d9655f709fca
Step 4/17 : ARG CUSTOM_ADMIN_PORT="${CUSTOM_ADMIN_PORT:-7001}"
 ---> Running in 7c89c18c5b6f
 ---> 63f77b7fae1e
Removing intermediate container 7c89c18c5b6f
Step 5/17 : ARG CUSTOM_MANAGED_SERVER_PORT="${CUSTOM_MANAGED_SERVER_PORT:-8001}"
 ---> Running in 6adf7289dcb3
 ---> 99de8db7bf80
Removing intermediate container 6adf7289dcb3
Step 6/17 : ARG CUSTOM_DEBUG_PORT="${CUSTOM_DEBUG_PORT:-8453}"
 ---> Running in cc22b2aa5c75
 ---> d582c1da59ab
Removing intermediate container cc22b2aa5c75
Step 7/17 : ARG CUSTOM_ADMIN_NAME="${CUSTOM_ADMIN_NAME:-admin-server}"
 ---> Running in ec0695270d75
 ---> a58485c81c3b
Removing intermediate container ec0695270d75
Step 8/17 : ARG CUSTOM_ADMIN_HOST="${CUSTOM_ADMIN_HOST:-wlsadmin}"
 ---> Running in e5c2beb95153
 ---> c395d6b73901
Removing intermediate container e5c2beb95153
Step 9/17 : ENV ORACLE_HOME /u01/oracle PROPERTIES_FILE_DIR "/u01/oracle/properties" DOMAIN_NAME "${CUSTOM_DOMAIN_NAME}" DOMAIN_HOME "/u01/oracle/user_projects/domains/${CUSTOM_DOMAIN_NAME}" ADMIN_PORT "${CUSTOM_ADMIN_PORT}" ADMIN_NAME "${CUSTOM_ADMIN_NAME}" ADMIN_HOST "${CUSTOM_ADMIN_HOST}" MANAGED_SERVER_PORT "${CUSTOM_MANAGED_SERVER_PORT}" MANAGED_SERV_NAME "${MANAGED_SERV_NAME}" DEBUG_PORT "8453" PATH $PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:${DOMAIN_HOME}:${DOMAIN_HOME}/bin:/u01/oracle
 ---> Running in 777a08427fd5
 ---> 5a92760006a6
Removing intermediate container 777a08427fd5
Step 10/17 : COPY container-scripts/* /u01/oracle/
 ---> 8283c304ca34
Removing intermediate container 8434dfc75655
Step 11/17 : USER root
 ---> Running in 91f11f8d0797
 ---> 1bc45c76dd19
Removing intermediate container 91f11f8d0797
Step 12/17 : RUN chmod +xw /u01/oracle/*.sh &&     chmod +xw /u01/oracle/*.py &&     mkdir -p ${PROPERTIES_FILE_DIR} &&     chown -R oracle:oracle ${PROPERTIES_FILE_DIR} &&     mkdir -p $DOMAIN_HOME &&     chown -R oracle:oracle $DOMAIN_HOME &&     chmod -R a+xwr $DOMAIN_HOME
 ---> Running in 52d91a36e5ec
 ---> 93bb84591892
Removing intermediate container 52d91a36e5ec
Step 13/17 : COPY properties/docker-build/domain*.properties ${PROPERTIES_FILE_DIR}/
 ---> c73dd0e0f1b4
Removing intermediate container 1a996483d761
Step 14/17 : RUN /u01/oracle/createWLSDomain.sh &&     echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     chmod -R a+x $DOMAIN_HOME/bin/*.sh  &&     rm ${PROPERTIES_FILE_DIR}/*.properties
 ---> Running in 0ac4c759d359
Domain Home is:  /u01/oracle/user_projects/domains/sample-domain1

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

cluster_name             : [cluster-1]
domain_path              : [/u01/oracle/user_projects/domains/sample-domain1]
domain_name              : [sample-domain1]
admin_server_name        : [admin-server]
admin_port               : [7001]
cluster_name             : [cluster-1]
server_port              : [8001]
number_of_ms             : [5]
cluster_type             : [DYNAMIC]
managed_server_name_base : [managed-server]
production_mode_enabled  : [true]
t3_channel_port          : [30012]
t3_public_address        : []
Configuring Dynamic Cluster cluster-1
Creating Server Template: cluster-1-template
Done creating Server Template: cluster-1-template
Done setting attributes for Dynamic Cluster: cluster-1
Domain Created
Domain Updated
Done


Exiting WebLogic Scripting Tool.

 ---> c046ff560b55
Removing intermediate container 0ac4c759d359
Step 15/17 : EXPOSE $ADMIN_PORT $MANAGED_SERVER_PORT $DEBUG_PORT
 ---> Running in dd729de24ea6
 ---> 4bb3f2a4ded1
Removing intermediate container dd729de24ea6
Step 16/17 : WORKDIR $DOMAIN_HOME
 ---> 5b3baa061eca
Removing intermediate container 6e4954d8a21d
Step 17/17 : CMD startAdminServer.sh
 ---> Running in cbbc96ff928d
 ---> 2c14241f78fe
Removing intermediate container cbbc96ff928d
Successfully built 2c14241f78fe

Create domain sample-domain1 successfully.

Domain sample-domain1 was created and will be started by the WebLogic Kubernetes Operator

The following files were generated:
  my-output/weblogic-domains/sample-domain1/create-domain-inputs.yaml
  my-output/weblogic-domains/sample-domain1/domain.yaml

Completed
bash-4.2$

**Comment by simon-meng-cn** [comment] 2019-04-12 13:23
I am sorry for my misinformation. You need check the existence of this file
/home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-build/domain.properties.

If the property file does not exist, copy /home/oracle/WERK/weblogic-domains/sample-domain1/domain.properties to that location. Then execute the create domain script with -k option.

**Comment by simon-meng-cn** [comment] 2019-04-15 10:13
Has the problem been solved?

**Comment by creativefre** [comment] 2019-04-15 12:46
The file was present but the build.sh script failed to call setEnv.sh with the right parameter (location of the domain.properties)

Thet's why I get the error property file not found. 

Location of the files:
build.sh: /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/build.sh
setEnv.sh: /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/container-scripts/setEnv.sh

What I did to fix it 

First I run ./create-domain.sh -i my-inputs.yaml -o my-output -u weblogic -p welcome1 

-> This still given the property file not found error

Then I go to /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/build.sh

and change the first line !#/bin/sh to !#/bin/bash

after that I run sudo build.sh

Then the image is created succesfully.

It's not the best fix but it works.

**Comment by simon-meng-cn** [comment] 2019-04-16 02:30
The operator sample code works fine for me. So I still don't know what caused this error. But I am very glad to hear you solve it. Can we close this issue?

**Closed** 2019-04-19 06:32 UTC

**Comment by jshum2479** [comment] 2019-05-06 15:55
I actually have the same problem and I think the problem is because of ubuntu shell has different support for sourcing the setEnv.    I changed to use source instead of dot, eg.  

source ../setEnv.sh .... in build.sh and it works fine.

**Comment by maleficarum** [comment] 2019-09-17 03:32
I'm dealing with the same issue, and it seems that the domain.properties is in the proper path ( ~/projects/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-build/domain.properties), and got the same error (A properties file with variable definitions should be supplied.); may I be creating the properties file in the wrong path ? Thanks.

**Comment by simon-meng-cn** [comment] 2019-09-17 05:14
According to previous comments, this issue may be related to the operating system and the shell. Can you try the solutions provided by creativefre and jshum2479?
