### ISSUE TITLE
Error preparing server: error opening listener: listen tcp :80: bind: permission denied

### ISSUE THREAD

**Issue by sp1d3rino** [oracle/weblogic-kubernetes-operator#1546] opened 2020-04-07 21:45 UTC
I reached the traefik installation but it fails on helm command:

```
helm install stable/traefik \
     --name traefik-operator \
     --namespace traefik \
     --values kubernetes/samples/charts/traefik/values.yaml  \
     --set "kubernetes.namespaces={traefik,weblogic}" \
     --wait
```

I get this error in the traefik-operator pod logs

`Error preparing server: error opening listener: listen tcp :80: bind: permission denied
`

any idea?

**Comment by lennyphan** [comment] 2020-04-08 17:45
What version of Helm are you using?  Did you give helm cluster role permissions?

**Comment by sp1d3rino** [comment] 2020-04-08 17:52
client/server both 2.9.0 
no I didn't give helm cluster role perm
what do you suggest to do?

**Comment by lennyphan** [comment] 2020-04-08 17:55
From the Quick Start guide, https://oracle.github.io/weblogic-kubernetes-operator/quickstart/install/:

$ cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-user-cluster-admin-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
EOF

Worth a try.

**Comment by sp1d3rino** [comment] 2020-04-08 18:12
no man

I just tried
```
$ oc get clusterrolebinding | grep helm
helm-cluster-admin                                                         3m

```
but the error is still present. I found that this should solve because the 80 port is a privileged prod(less than 1024)

`setcap 'cap_net_bind_service=+ep' $(which traefik)`

but I don't know how to execute that command in the POD.

**Comment by tbarnes-us** [comment] 2021-03-29 21:33
I'm sorry your last post did not get a response, but I'm assuming the issue is resolved by now.   Feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:33 UTC
