### ISSUE TITLE
provide better guidance on when to use root

### ISSUE THREAD

**Issue by markxnelson** [oracle/weblogic-kubernetes-operator#56] opened 2018-02-02 14:43 UTC
From Hadi, 
In the documentation, try to make it a bit clearer when you have to use root or sudo and when to use a normal user.

**Comment by tbarnes-us** [comment] 2021-03-29 22:41
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

**Closed by tbarnes-us** 2021-03-29 22:41 UTC
Labels: customer reported, documentation, polish
