### ISSUE TITLE
Apache, Voyager,  and Traefik should be set for TLS out of the box.

### ISSUE THREAD

**Issue by mriccell** [oracle/weblogic-kubernetes-operator#317] opened 2018-05-27 19:20 UTC
This is a usability requirement from Antonio from CERN.
Traefik, Voyager,  and Apache are listening on http. It would be nice have them already setup for TLS.
This requires that both these LBs have SSL enabled by default.

**Comment by tbarnes-us** [comment] 2021-03-29 22:24
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect. For example, I think we've provided doc/samples for terminating SSL at the LB.

**Closed by tbarnes-us** 2021-03-29 22:24 UTC
