### ISSUE TITLE
Add new properties in the sample scripts to be used to create domain for Oracle Identity Governance

### ISSUE THREAD

**Issue by tanmaygarg-oracle** [oracle/weblogic-kubernetes-operator#1836] opened 2020-07-29 15:27 UTC
We need the following properties to be added in the operator samples under  # extra entries for FMW Infra domains in common/utility.sh

frontEndHost
frontEndPort

code required to be added

sed -i -e "s:%FRONTEND_HOST%:${frontEndHost}:g" ${createJobOutput}
sed -i -e "s:%FRONTEND_PORT%:${frontEndPort}:g" ${createJobOutput}

**Comment by tbarnes-us** [comment] 2021-03-29 20:59
I'm assuming the issue is resolved by now and the consequent enhancement is now available in a public release. 

Feel free to re-open the issue if I'm incorrect.

**Closed by tbarnes-us** 2021-03-29 20:59 UTC
