### ISSUE TITLE
Document requirements for custom docker images

### ISSUE THREAD

**Issue by anilarora** [oracle/weblogic-kubernetes-operator#1239] opened 2019-09-04 18:05 UTC
It's not clear what are the exact requirements for custom docker images.  At the moment, it seems like there's an assumption that the custom image extends one of the official images.  If the custom image does not extend these images, there needs to be some requirements on what is expected in terms of file layout, environment variables, etc.

**Comment by tbarnes-us** [comment] 2021-03-29 21:53
I don't think extending an official image is required. The main requirement is that WLS be at PS4, or, if at PS3, that certain patches be installed (see the WKO doc).  Note that leveraging the 'WebLogic Image Tool' to create your image is highly recommended.  

Regardless, I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:53 UTC

**Comment by tbarnes-us** [comment] 2021-03-29 22:08
@rosemarymarano @rjeberhard FYI
