### ISSUE TITLE
no matches for kind "Domain" in version "weblogic.oracle/v8"

### ISSUE THREAD

**Issue by xxhoffmann** [oracle/weblogic-kubernetes-operator#2212] opened 2021-02-22 12:34 UTC
Our model.yaml are generated by preparemodel.sh script

running : kubectl apply -f model.yaml
error: unable to recognize "model.yaml": no matches for kind "Domain" in version "weblogic.oracle/v8"

Model.yaml:
apiVersion: "weblogic.oracle/v8"
kind: Domain

**Comment by jshum2479** [comment] 2021-02-22 14:01
What version of operator have you installed?  This looks like the domain crd is not there for v8.   Can you try `kubectl explain domain` .   You can also get the crd definition by  `kubectl describe crd domains.weblogic.oracle` and look for Versions.Name

**Comment by tbarnes-us** [comment] 2021-03-29 19:40
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public `#operator` slack channel at `oracle-weblogic.slack.com` (sign-up here:  `https://weblogic-slack-inviter.herokuapp.com/`).

**Closed by tbarnes-us** 2021-03-29 19:40 UTC
