### ISSUE TITLE
DOMAIN_HOME directory not found '/u01/oracle/user_projects/domains/sample-domain1'

### ISSUE THREAD

**Issue by alexis-rodriguez-21** [oracle/weblogic-kubernetes-operator#2207] opened 2021-02-18 22:10 UTC
Hi,
I am following "Quick Start" in the documentation https://oracle.github.io/weblogic-kubernetes-operator/quickstart/
All the steps till "Prepare for a Domain" works fine.
During "Create a Domain", I am getting error. When I see "sample-domain1-ns", the pod sample-domain1-introspect-domain-job-xxxx showing status as "Terminated: Error"
In the logs, I find following line at the end:
Error: missing DOMAIN_HOME directory '/u01/oracle/user_projects/domains/sample-domain1'.

adjunto mi domain.yaml and my-input.yaml
[
[domain.yaml.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/6006186/domain.yaml.txt)
[my-input.yaml.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/6006187/my-input.yaml.txt)

](url)

**Comment by bhavaniravichandran** [comment] 2021-02-19 17:47
Can you please add a few more lines from the logs or attach the log? Did you see any other error message when you ran create-domain.sh?

**Comment by alexis-rodriguez-21** [comment] 2021-02-19 17:52
of Course, these are the domain logs 
![image](https://user-images.githubusercontent.com/78376955/108541913-ab5cf400-72a8-11eb-9591-13edfaf33482.png)

**Comment by alexis-rodriguez-21** [comment] 2021-02-19 17:58
I do not see any other error in the creation logs, I also attach everything that throws me.
[logs-create-domain.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/6011975/logs-create-domain.txt)

**Comment by bhavaniravichandran** [comment] 2021-02-19 18:00
The log doesn't have much information. Are you running this in a linux box or in a cloud environment?

**Comment by alexis-rodriguez-21** [comment] 2021-02-19 18:02
In Google Cloud Platform

**Comment by bhavaniravichandran** [comment] 2021-02-19 18:08
If you are running this in a cloud, then you have to create the domain image first, push the image to a registry  and then create the domain.
create-domain.sh -i "your-inputs.yaml" -o "dir where domain.yaml will be created" -u "weblogic username" -p "weblogic-password"  - This command will create the domain image for you. You then have to push the image to an external registry and then when you "kubectl apply -f "the domain yaml file", the domain should start.
Let me know if this works.

**Comment by alexis-rodriguez-21** [comment] 2021-02-19 18:41
This is the process I did
#docker run -d -p 5000: 5000 --name registry registry: 2
#docker pull container-registry.oracle.com/middleware/weblogic:12.2.1.4
#docker image tag container-registry.oracle.com/middleware/weblogic:12.2.1.4 localhost: 5000 / myfirstimage
#docker push localhost: 5000 / myfirstimage
#docker pull localhost: 5000 / myfirstimage
#. / create-domain.sh -i create-domain-inputs.yaml -o / home / alexis_rodriguez_condor / weblogic-kubernetes-operator / kubernetes / samples / scripts / create-weblogic-domain / domain-home-in-image - u weblogic -p Welcome1 -e
Is it the correct process? because I change the file create-domain-inputs.yaml to always download the image and add a secret since it gives me a previous error in which it said that it could not find the image, but it was resolved after that

**Comment by alexis-rodriguez-21** [comment] 2021-02-19 18:49
this is the previous error
Message: rpc error: code = Unknown desc = Error response from daemon: Get http: // localhost: 5000 / v2 /: dial tcp [:: 1]: 5000: connect: connection refused
Reason: ErrImagePull

**Comment by bhavaniravichandran** [comment] 2021-02-19 18:57
The image (myfirstimage) you pushed to the registry is the weblogic image. When you run create-domain.sh without the -e option, it will create an image with the domain in  it. But I see the problem with your input-yaml. The following line in your input yaml needs to be fixed -
image: container-registry.oracle.com/middleware/weblogic:12.2.1.4
You should give an image name for your domain here -example - sample-domain-in-image:1.0
After fixing your input yaml, run create-domain.sh command without  -e option. You will see an image "sample-domain-in-image:1.0" created in your local. You have to push this to your registry (after tagging it if needed). Then apply the domain.yaml that was created.

**Comment by alexis-rodriguez-21** [comment] 2021-02-23 05:14
I tried to deploy weblogic following your instructions, but I found a problem that could not be solved. the $ HOME_DOMAIN for the version container-registry.oracle.com/middleware/weblogic:12.2.1.4
It seems to be / u01 / oracle / user_projects / domains / base_domain, I deployed the image over docker and it is the path that creates me, how can I go about changing that path?

**Comment by bhavaniravichandran** [comment] 2021-02-23 15:42
Can you capture the output of create-domain.sh and post it here?

**Comment by alexis-rodriguez-21** [comment] 2021-02-23 17:08
![image](https://user-images.githubusercontent.com/78376955/108878758-30584e00-75c6-11eb-9a13-d96db54702c2.png)
This is the new error that appears to me, the only thing that I see strange is that in the data-home = in the domain.yaml file it appears empty

output create-domain.sh
./create-domain.sh -i my-domain.yaml -o /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image -u weblogic -p welcome1
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export sslEnabled="false"
export adminPort="7001"
export adminServerSSLPort="7002"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="2"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export managedServerSSLPort="8002"
export productionModeEnabled="true"
export image="weblogic-sample-domain1"
export imagePullPolicy="Always"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export httpAccessLogInLogHome="true"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="us-ashburn-1.ocir.io/ideg6oammkap/images/weblogic:2.0.test"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"
export serverPodMemoryRequest="768Mi"
export serverPodCpuRequest="250m"
export istioEnabled="false"
export istioReadinessPort="8888"

Cloning into './docker-images'...
remote: Enumerating objects: 13664, done.
remote: Total 13664 (delta 0), reused 0 (delta 0), pack-reused 13664
Receiving objects: 100% (13664/13664), 9.82 MiB | 22.45 MiB/s, done.
Resolving deltas: 100% (8007/8007), done.
Generating /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/weblogic-domains/sample-domain1/domain.properties
Generating /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
Export environment variables from the /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-build/domain.properties properties file
 env_arg: CUSTOM_DOMAIN_NAME=sample-domain1
 env_arg: CUSTOM_SSL_ENABLED=false
 env_arg: CUSTOM_ADMIN_NAME=admin-server
 env_arg: CUSTOM_ADMIN_HOST=wlsadmin
 env_arg: CUSTOM_ADMIN_SERVER_SSL_PORT=7002
 env_arg: CUSTOM_MANAGED_SERVER_SSL_PORT=8002
 env_arg: CUSTOM_DEBUG_PORT=8453
 env_arg: CUSTOM_IMAGE_TAG=weblogic-sample-domain1
 env_arg: CUSTOM_CLUSTER_NAME=cluster-1
 env_arg: CUSTOM_CLUSTER_TYPE=DYNAMIC
BUILD_ARG= --build-arg CUSTOM_DOMAIN_NAME=sample-domain1 --build-arg CUSTOM_SSL_ENABLED=false --build-arg CUSTOM_ADMIN_NAME=admin-server --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_SERVER_SSL_PORT=7002 --build-arg CUSTOM_ADMIN_SERVER_SSL_PORT=7002 --build-arg CUSTOM_ADMIN_SERVER_SSL_POR
T=7002 --build-arg CUSTOM_MANAGED_SERVER_SSL_PORT=8002 --build-arg CUSTOM_DEBUG_PORT=8453 --build-arg CUSTOM_CLUSTER_NAME=cluster-1 --build-arg CUSTOM_CLUSTER_TYPE=DYNAMIC
CUSTOM_IMAGE_TAG  weblogic-sample-domain1
Sending build context to Docker daemon   47.1kB
Step 1/22 : FROM  us-ashburn-1.ocir.io/ideg6oammkap/images/weblogic:2.0.test
2.0.test: Pulling from ideg6oammkap/images/weblogic
980316e41237: Pull complete
ac33ca03694c: Pull complete
ae2952e191c0: Pull complete
b61ff752d3b9: Pull complete
0dad7b9fa39d: Pull complete
813997680955: Pull complete
Digest: sha256:d86f15b67a09d38700eb043d5279f6eaa1bb60bfdc10b1f682885da161127bb7
Status: Downloaded newer image for us-ashburn-1.ocir.io/ideg6oammkap/images/weblogic:2.0.test
 ---> bedcd66c678e
Step 2/22 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Running in 1aaa52b1b69a
Removing intermediate container 1aaa52b1b69a
 ---> 47b539eec845
Step 3/22 : ARG CUSTOM_DOMAIN_NAME="${CUSTOM_DOMAIN_NAME:-domain1}"
 ---> Running in 37cc2b0baeb0
Removing intermediate container 37cc2b0baeb0
 ---> 7ff67bd79768
Step 4/22 : ARG CUSTOM_ADMIN_PORT="${CUSTOM_ADMIN_PORT:-7001}"
 ---> Running in c7435662e28c
Removing intermediate container c7435662e28c
 ---> 9b71dba0494c
Step 5/22 : ARG CUSTOM_ADMIN_SERVER_SSL_PORT="${CUSTOM_ADMIN_SERVER_SSL_PORT:-7002}"
 ---> Running in e18ce77a4cc9
Removing intermediate container e18ce77a4cc9
 ---> 612c4a56b2a8
Step 6/22 : ARG CUSTOM_MANAGED_SERVER_PORT="${CUSTOM_MANAGED_SERVER_PORT:-8001}"
 ---> Running in 6b71720e399f
Removing intermediate container 6b71720e399f
 ---> 3644f5da1349
Step 7/22 : ARG CUSTOM_MANAGED_SERVER_SSL_PORT="${CUSTOM_MANAGED_SERVER_SSL_PORT:-8002}"
 ---> Running in 2d967a9182ff
Removing intermediate container 2d967a9182ff
 ---> daa62e3142f8
Step 8/22 : ARG CUSTOM_DEBUG_PORT="${CUSTOM_DEBUG_PORT:-8453}"
 ---> Running in b8906e64b1d0
Removing intermediate container b8906e64b1d0
 ---> 9a2654a47e63
Step 9/22 : ARG CUSTOM_ADMIN_NAME="${CUSTOM_ADMIN_NAME:-admin-server}"
 ---> Running in 8599eff02ed7
Removing intermediate container 8599eff02ed7
 ---> 68b0b2fb4b2e
Step 10/22 : ARG CUSTOM_ADMIN_HOST="${CUSTOM_ADMIN_HOST:-wlsadmin}"
 ---> Running in 26ed2607cced
Removing intermediate container 26ed2607cced
 ---> bb32a421a984
Step 11/22 : ARG CUSTOM_CLUSTER_NAME="${CUSTOM_CLUSTER_NAME:-DockerCluster}"
 ---> Running in 011d91c929e5
Removing intermediate container 011d91c929e5
 ---> fa0105a6cfb3
Step 12/22 : ARG CUSTOM_SSL_ENABLED="${CUSTOM_SSL_ENABLED:-false}"
 ---> Running in 7b20b65ef996
Removing intermediate container 7b20b65ef996
 ---> 8baca8133b73
Step 13/22 : ENV ORACLE_HOME=/u01/oracle     PROPERTIES_FILE_DIR="/u01/oracle/properties"     SSL_ENABLED="${CUSTOM_SSL_ENABLED}"     DOMAIN_NAME="${CUSTOM_DOMAIN_NAME}"     DOMAIN_HOME="/u01/oracle/user_projects/domains/${CUSTOM_DOMAIN_NAME}"     ADMIN_PORT="${CUSTOM_ADMIN_PORT}"     ADMIN_SERVER_SSL_PORT="${CUSTOM_ADMIN_SERVER_SSL_PORT}"     ADMIN_NAME="${CUSTOM_ADMIN_NAME}"     ADMIN_HOST="${CUSTOM_ADMIN_HOST}"     CLUSTER_NAME="${CUSTOM_CLUSTER_NAME}"     MANAGED_SERVER_PORT="${CUSTOM_MANAGED_SERVER_PORT}"     MANAGED_SERVER_SSL_PORT="${CUSTOM_MANAGED_SERVER_SSL_PORT}"     MANAGED_SERV_NAME="${CUSTOM_MANAGED_SERV_NAME}"     DEBUG_PORT="8453"     PATH=$PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:${DOMAIN_HOME}:${DOMAIN_HOME}/bin:/u01/oracle
 ---> Running in 9f5333d76246
Removing intermediate container 9f5333d76246
 ---> 1196170f01f6
Step 14/22 : COPY --chown=oracle:root container-scripts/* /u01/oracle/
 ---> 2d6ab93ddad5
Step 15/22 : USER root
 ---> Running in d831875052ed
Removing intermediate container d831875052ed
 ---> 2d523d43af7d
Step 16/22 : RUN chmod +xw /u01/oracle/*.sh &&     chmod +xw /u01/oracle/*.py &&     mkdir -p ${PROPERTIES_FILE_DIR} &&     mkdir -p $DOMAIN_HOME &&     chown -R oracle:root $DOMAIN_HOME/.. &&     chown -R oracle:root ${PROPERTIES_FILE_DIR}
 ---> Running in e93454446746
Removing intermediate container e93454446746
 ---> e56b9cb877d6
Step 17/22 : COPY --chown=oracle:root properties/docker-build/domain*.properties ${PROPERTIES_FILE_DIR}/
 ---> 79382ccd3e48
Step 18/22 : USER oracle
 ---> Running in 382f7e42a74a
Removing intermediate container 382f7e42a74a
 ---> 3d72a1977291
Step 19/22 : RUN /u01/oracle/createWLSDomain.sh &&     chmod -R g+w $DOMAIN_HOME &&     echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     rm ${PROPERTIES_FILE_DIR}/*.properties
 ---> Running in 90f7c1d50a92
Domain Home is:  /u01/oracle/user_projects/domains/sample-domain1

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

cluster_name             : [cluster-1]
domain_path              : [/u01/oracle/user_projects/domains/sample-domain1]
domain_name              : [sample-domain1]
ssl_enabled              : [false]
admin_server_name        : [admin-server]
admin_port               : [7001]
admin_server_ssl_port    : [7002]
cluster_name             : [cluster-1]
server_port              : [8001]
managed_server_ssl_port  : [8002]
number_of_ms             : [5]
cluster_type             : [DYNAMIC]
managed_server_name_base : [managed-server]
production_mode_enabled  : [true]
t3_channel_port          : [30012]
t3_public_address        : []
Configuring Dynamic Cluster cluster-1
Creating Server Template: cluster-1-template
Done creating Server Template: cluster-1-template
Done setting attributes for Dynamic Cluster: cluster-1
Domain Created
Domain Updated
Done


Exiting WebLogic Scripting Tool.

Removing intermediate container 90f7c1d50a92
 ---> 1ae7eeeab043
Step 20/22 : EXPOSE $ADMIN_PORT $ADMIN_SERVER_SSL_PORT $MANAGED_SERVER_PORT $MANAGED_SERVER_SSL_PORT $DEBUG_PORT
 ---> Running in c8d36a4fa6f7
Removing intermediate container c8d36a4fa6f7
 ---> 603d884d7d3e
Step 21/22 : WORKDIR $DOMAIN_HOME
 ---> Running in d8f9020e5f05
Removing intermediate container d8f9020e5f05
 ---> 3152b45d5aba
Step 22/22 : CMD ["startAdminServer.sh"]
---> Running in f2f55695bf73
Removing intermediate container f2f55695bf73
 ---> 3bff2551a848
[Warning] One or more build-args [CUSTOM_CLUSTER_TYPE] were not consumed
Successfully built 3bff2551a848
Successfully tagged weblogic-sample-domain1:latest

Create domain sample-domain1 successfully.

Domain sample-domain1 was created and will be started by the WebLogic Kubernetes Operator

The following files were generated:
  /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/weblogic-domains/sample-domain1/create-domain-inputs.yaml
  /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/weblogic-domains/sample-domain1/domain.yaml

Completed

**Comment by alexis-rodriguez-21** [comment] 2021-02-23 17:52
![image](https://user-images.githubusercontent.com/78376955/108885567-9a282600-75cd-11eb-8e7c-4a7f6df42920.png)

**Comment by bhavaniravichandran** [comment] 2021-02-23 17:52
I do see that the domain is created at the correct place. If you run kubectl apply -f /home/alexis_rodriguez_condor/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/weblogic-domains/sample-domain1/domain.yaml, do you see the same error? Also run the following command to see if the domain is created in the image-
docker run -ti weblogic-sample-domain1:latest /bin/bash
Check if the domain is created in the right place.

**Comment by tbarnes-us** [comment] 2021-03-29 19:44
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 19:44 UTC
