### ISSUE TITLE
not able to pull the store/oracle/serverjre:8 image

### ISSUE THREAD

**Issue by rbaumgar** [oracle/weblogic-kubernetes-operator#141] opened 2018-03-07 13:46 UTC
I try to build the operator image without any success, because I can not pull the image, after successful login...

$ docker build -t weblogic-kubernetes-operator:developer --no-cache=true .
Sending build context to Docker daemon 96.39 MB
Step 1 : FROM store/oracle/serverjre:8
Trying to pull repository registry.access.redhat.com/store/oracle/serverjre ... 
Trying to pull repository docker.io/store/oracle/serverjre ... 
Pulling repository docker.io/store/oracle/serverjre
Error: image store/oracle/serverjre:8 not found
$ docker -D pull store/oracle/serverjre:8 
Trying to pull repository registry.access.redhat.com/store/oracle/serverjre ... 
Trying to pull repository docker.io/store/oracle/serverjre ... 
Pulling repository docker.io/store/oracle/serverjre
Error: image store/oracle/serverjre:8 not found

I can find the download instruction on the web UI

**Comment by markxnelson** [comment] 2018-03-07 14:05
Hi @rbaumgar, did you go to the Docker Store and accept the license agreement for the serverjre image, as described in the doc here: https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/installation.md

**Comment by markxnelson** [comment] 2018-03-07 14:06
Here is the link directly to that image: https://store.docker.com/images/oracle-serverjre-8

**Comment by rbaumgar** [comment] 2018-03-07 14:59
Yes! now two times!
I did also a logout and login.
I also not able to download store/oracle/weblogic:12.2.1.3.
no problem with the Oracle registry
$ docker pull container-registry.oracle.com/java/serverjre
Using default tag: latest
Trying to pull repository container-registry.oracle.com/java/serverjre ... 
latest: Pulling from container-registry.oracle.com/java/serverjre
8dc3ae811b63: Downloading [======================================>            ] 31.56 MB/41.44 MB
ca7c99ed0ff8: Downloading [===========>                                       ] 12.77 MB/57.68 MB

**Comment by markxnelson** [comment] 2018-03-07 15:13
Just checking, I think it should be:

`docker pull store/oracle/serverjre:8`

**Comment by rbaumgar** [comment] 2018-03-07 15:35
same result :-(
$ docker pull store/oracle/serverjre
Using default tag: latest
Trying to pull repository registry.access.redhat.com/store/oracle/serverjre ... 
Trying to pull repository docker.io/store/oracle/serverjre ... 
Pulling repository docker.io/store/oracle/serverjre
Error: image store/oracle/serverjre:latest not found

**Comment by markxnelson** [comment] 2018-03-07 15:51
The tag is not latest. You need that ":8" on the end of the pull command

**Comment by markxnelson** [comment] 2018-03-07 15:51
The tag is not latest. You need that ":8" on the end of the pull command

**Comment by rjeberhard** [comment] 2018-03-07 16:49
I've just verified that I can pull this image today using:

docker pull store/oracle/serverjre:8

As Mark noted, you do need to visit the store page and click through to "purchase" the image and then docker login locally.  If this still isn't working for you once you add the ":8" tag, I wonder if your network has a proxy server?

**Comment by rbaumgar** [comment] 2018-03-12 08:47
In the meantime I have 3(!) entitlements, but I still get the same problem.

Is the store on docker.io? You see that my docker configured only for docker.io. When I try to conntct to store.docker.com, I get an error...

$ docker login store.docker.com
Username (rbaumgar@redhat.com): rbaumgar@redhat.com
Password: 
Login Succeeded
$ docker -D pull store/oracle/serverjre:8
Trying to pull repository registry.access.redhat.com/store/oracle/serverjre ... 
Trying to pull repository docker.io/store/oracle/serverjre ... 
Pulling repository docker.io/store/oracle/serverjre
Error: image store/oracle/serverjre:8 not found
$ docker -D pull store.docker.com/store/oracle/serverjre:8
Trying to pull repository store.docker.com/store/oracle/serverjre ... 
Pulling repository store.docker.com/store/oracle/serverjre
invalid character '<' looking for beginning of value

**Comment by rbaumgar** [comment] 2018-03-12 13:16
interesting, to close without any help!
I tried it from multiple networks, my company, customer and at home...

Mit freundlichen Grüßen / Kind regards


Robert Baumgartner

Senior Solution Architect Middleware

Red Hat Austria GmbH <https://www.redhat.com>

Millenniumtower 24.Stock

Handelskai 94-96

A-1200 Wien

robert.baumgartner@redhat.com    M: +43-660-5913883
<https://red.ht/sig>

**Comment by mriccell** [comment] 2018-03-12 13:35
Did you login to Docker Store from your command line?
Before you can pull this image from the Docker Store, you need to make sure your Docker client has logged in successfully using the docker login command:

# docker login
Username: <Docker Hub/Store Username>
Password: <Docker Hub/Store Password>
Login successful.

Once you have successfully logged in, you can pull the Oracle Server JRE image from the Docker Store:

docker pull store/oracle/serverjre:8

Hope this helps

**Comment by mriccell** [comment] 2018-03-12 13:38
Instructions in the Docker Store
Before you can pull this image from the Docker Store, you need to make sure your Docker client has logged in successfully using the docker login command:

# docker login
Username: <Docker Hub/Store Username>
Password: <Docker Hub/Store Password>
Login successful.

Once you have successfully logged in, you can pull the Oracle Server JRE image from the Docker Store:

docker pull store/oracle/serverjre:8

I am not sure why the error, I will contact someone in the Docker team to see why you would be running into this issue.

Monica

**Comment by eviking** [comment] 2018-03-12 21:14
Robert

I just tried to copy and paste the commands that you posted and everything ran without any problems. 

$ docker login 
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (X): 
Password: 
Login Succeeded

$ docker -D pull store/oracle/serverjre:8
8: Pulling from store/oracle/serverjre
4040fe120662: Pull complete 
42c95984fa90: Pull complete 
Digest: sha256:f4edea6b86836c3e6d7f9f5b789c133e85343ed8af0295dde86794de3d7ca983
Status: Downloaded newer image for store/oracle/serverjre:8

Can you please include the output from <B>$docker info</B>, <B>$docker version</B> and your docker config files?

Can you pull any other images from Docker Hub and Docker Store? 

I noticed that your docker username is rbaumgar@redhat.com. Are you running RedHat's own distro of Docker? See (3)
https://rhelblog.redhat.com/2015/04/15/understanding-the-changes-to-docker-search-and-docker-pull-in-red-hat-enterprise-linux-7-1/


Thanks
 Jens

**Comment by rbaumgar** [comment] 2018-03-12 21:53
Jens,

first I have a docker id and I have needed entitlements, see screenshot

I tried to login to store.docker.com, hub.docker.com, without any success.
But I get "Login Succeeded"
I tried with two different version docker clients, without success
I tried different urls, without success
No problem download from docker.io, oracle-registry, ...

$ docker -D pull store/oracle/serverjre:8
Trying to pull repository registry.access.redhat.com/store/oracle/serverjre
...
Trying to pull repository docker.io/store/oracle/serverjre ...
Pulling repository docker.io/store/oracle/serverjre
Error: image store/oracle/serverjre:8 not found
$ docker -D pull store.docker.com/store/oracle/serverjre:8
Trying to pull repository store.docker.com/store/oracle/serverjre ...
Pulling repository store.docker.com/store/oracle/serverjre
invalid character '<' looking for beginning of value
$ docker -D pull hub.docker.com/store/oracle/serverjre:8
Trying to pull repository hub.docker.com/store/oracle/serverjre ...
Pulling repository hub.docker.com/store/oracle/serverjre
invalid character '<' looking for beginning of value

$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: RHEL7CSB-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.236 GB
 Data Space Total: 100.8 GB
 Data Space Available: 97.52 GB
 Metadata Space Used: 446.5 kB
 Metadata Space Total: 511.7 MB
 Metadata Space Available: 511.3 MB
 Thin Pool Minimum Free Space: 10.08 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host overlay null
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-693.11.6.el7.x86_64
Operating System: Employee SKU
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 18.88 GiB
Name: rbaumgar.remote.csb
ID: MFCX:TMEH:Y5RU:6G7X:OP7O:ZNN5:GZD2:6R3T:PT5P:GMEB:3ABO:MEFE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 docker-registry-default.192.168.122.111.xip.io
 172.30.0.0/16
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)
$ docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.x86_64
 Go version:      go1.7.6
 Git commit:      88a4867/1.12.6
 Built:           Mon Jun 19 17:26:57 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.x86_64
 Go version:      go1.7.6
 Git commit:      88a4867/1.12.6
 Built:           Mon Jun 19 17:26:57 2017
 OS/Arch:         linux/amd64
$ ~/Downloads/docker version
Client:
 Version:      17.03.2-ce
 API version:  1.24 (downgraded from 1.27)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24 (minimum version )
 Go version:   go1.7.6
 Git commit:   88a4867/1.12.6
 Built:        Mon Jun 19 17:26:57 2017
 OS/Arch:      linux/amd64
 Experimental: false


Mit freundlichen Grüßen / Kind regards


Robert Baumgartner

Senior Solution Architect Middleware

Red Hat Austria GmbH <https://www.redhat.com>

Millenniumtower 24.Stock

Handelskai 94-96

A-1200 Wien

robert.baumgartner@redhat.com    M: +43-660-5913883
<https://red.ht/sig>

**Comment by eviking** [comment] 2018-03-12 22:35
I can't tell if you are running RedHat's Docker distro on the server or the standard one from Docker, but in any case it is a very old version and it is clear that it has some RedHat specific configuration that defaults it to look at RedHat's repo first. 

Please try the following for me. 

Download the latest version of Docker for the server from Docker.com and remove any old configurations. Once we get that working we can start to narrow in on what the actually issue with your setup. I just want to get to a point where we have a working baseline. 

Thanks
 Jens

**Comment by rbaumgar** [comment] 2018-03-12 22:52
Jens,

you see that I am using a second client
Client:
 Version:      17.03.2-ce
 API version:  1.24 (downgraded from 1.27)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

And it does not work either.
I hope you will not tell me I have to change the server version, to
download something from the store!?!?!
​

**Comment by markxnelson** [comment] 2018-03-13 00:19
I think there might be an issue on the store side.  I just deleted the image and tried to pull it again, and I get the same error message about the '<' character.

```
$ docker -D pull store.docker.com/store/oracle/serverjre:8
Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!doctype html>\n<html lang=\"en\">\n\n<head>\n    <meta charset=\"utf-8\">\n    <title>404 : Docker</title>\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <style>\n    * {\n        line-height: 1.2;\n        margin: 0;\n    }\n\n    html {\n        color: #71859d;\n        display: table;\n        height: 100%;\n        text-align: center;\n        width: 100%;\n    }\n\n    body {\n        background: #fff;\n        dis  ......
```
Even after I do a successful `docker login` I get this same response...

**Comment by markxnelson** [comment] 2018-03-13 00:20
Oh hold on, if I change the command to this:

`docker -D pull store/oracle/serverjre:8`

Then it works

**Comment by markxnelson** [comment] 2018-03-13 00:24
I went to docker store and created a brand new user... 

```
marnelso@MARNELSO-mac web (accessibility) $ docker rmi store/oracle/serverjre:8
Untagged: store/oracle/serverjre:8
Untagged: store/oracle/serverjre@sha256:f4edea6b86836c3e6d7f9f5b789c133e85343ed8af0295dde86794de3d7ca983
Deleted: sha256:d747305fda455f81412fd1e767f48ff443f9042c8c528ea83f00b7c410fa78f6
Deleted: sha256:78c38aa649b164ec5af4f51d4b07f731a2eb2ed53aafa1b9f09cc6661c800257
marnelso@MARNELSO-mac web (accessibility) $ docker logout
Removing login credentials for https://index.docker.io/v1/
marnelso@MARNELSO-mac web (accessibility) $ docker -D pull store/oracle/serverjre:8
Error response from daemon: pull access denied for store/oracle/serverjre, repository does not exist or may require 'docker login'
marnelso@MARNELSO-mac web (accessibility) $ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: markxnelson2
Password:
Login Succeeded
marnelso@MARNELSO-mac web (accessibility) $ docker -D pull store/oracle/serverjre:8
Error response from daemon: pull access denied for store/oracle/serverjre, repository does not exist or may require 'docker login'
marnelso@MARNELSO-mac web (accessibility) $ # now i went and got the entitlement in the browser...
```
![image](https://user-images.githubusercontent.com/6345393/37316037-4d11735e-2633-11e8-897f-48fc159062c8.png)


```
marnelso@MARNELSO-mac web (accessibility) $ # now i went and got the entitlement in the browser...
marnelso@MARNELSO-mac web (accessibility) $ docker -D pull store/oracle/serverjre:8
8: Pulling from store/oracle/serverjre
4040fe120662: Already exists
42c95984fa90: Pull complete
Digest: sha256:f4edea6b86836c3e6d7f9f5b789c133e85343ed8af0295dde86794de3d7ca983
Status: Downloaded newer image for store/oracle/serverjre:8
marnelso@MARNELSO-mac web (accessibility) $
```

Appears to work as expected

**Comment by markxnelson** [comment] 2018-03-13 00:25
I am going to install 1.12.6 and try that...

**Comment by markxnelson** [comment] 2018-03-13 00:33
Installed brand new ubuntu, installed docker 1.12.6 (as per your docker version output above), tried to pull, "not found", did `docker login` and tried to pull, worked..

**Comment by markxnelson** [comment] 2018-03-13 00:34
@rbaumgar as you can see I have tried different users, different versions of docker, different OS, different computer, and I still cannot reproduce the issue.  I think there must be something about your particular environment.  Can you pull other images from docker store?  Can you try a different computer?

**Comment by markxnelson** [comment] 2018-03-13 00:36
I am going to download RHEL and try there..

**Comment by eviking** [comment] 2018-03-13 01:15
@rbaumgar Please follow the directions on https://docs.docker.com/install/linux/docker-ce/fedora/. Everything points in the direction of a configuration/RHEL version issue with the  Docker Server you are running. I can not help you unless you are willing to be helped.

**Comment by rbaumgar** [comment] 2018-03-13 11:43
Mark,
it has nothing to do with my (old) docker version and/or configuration!
The only required thing is the docker login against the correct URL and username(not mail)

$ docker login **docker.io**
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: **rbaumgar**
Password: 
Login Succeeded
$ docker -D pull store/oracle/serverjre:8
Trying to pull repository registry.access.redhat.com/store/oracle/serverjre ... 
Trying to pull repository docker.io/store/oracle/serverjre ... 
8: Pulling from docker.io/store/oracle/serverjre
4040fe120662: Pulling fs layer 
42c95984fa90: Pulling fs layer 
...

**Comment by markxnelson** [comment] 2018-03-13 12:21
Hi Robert, 
Great, I am happy you got it to work.  I am going to close this issue now.  Please contact us again if you have any other issues. 

If you are planning to do more work with the operator, please allow me to reming you of the clearly stated supported version of docker, which is listed in the readme here: 

https://github.com/oracle/weblogic-kubernetes-operator#requirements

`Docker 17.03.1.ce`

If you are using a different version of docker, we may ask you to reproduce any issues using a supported version.

**Closed by markxnelson** 2018-03-13 12:21 UTC
Labels: help wanted

**Comment by tareynoso** [comment] 2019-08-07 16:06
Hi, I got the same issues.I went like @rbaumgar said to docker.com, logged and search for  oracle-serverjre-8/
I had to select, fill the requirements, name, phone and thing like this, also accept agree the terms.
Then it's allows me to download the image
docker pull store/oracle/serverjre:8
