### ISSUE TITLE
adminService annotations and labels not working

### ISSUE THREAD

**Issue by csegedicsaba** [oracle/weblogic-kubernetes-operator#2010] opened 2020-10-26 16:26 UTC
**adminService** annotation and label are not present on the created service for admin server.

    adminServer:
      serverStartState: "RUNNING"
      adminService:
        annotations:
          test: test
        labels:
          test: test

kubectl describe service test-domain-admin-server:

    Name:              test-domain-admin-server
    Namespace:         default
    Labels:            serviceType=SERVER
                       weblogic.createdByOperator=true
                       weblogic.domainName=test-domain
                       weblogic.domainUID=test-domain
                       weblogic.serverName=admin-server
    Annotations:       service.alpha.kubernetes.io/tolerate-unready-endpoints: true
                       weblogic.sha256: 7e7e157bb92df685363fea3964bc80f1720094ba7e2796747af844709390c232
    Selector:          weblogic.createdByOperator=true,weblogic.domainUID=test-domain,weblogic.serverName=admin-server
    Type:              ClusterIP
    IP:                None
    Port:              default-secure  7002/TCP
    TargetPort:        7002/TCP
    Endpoints:         10.1.1.3:7002
    Session Affinity:  None
    Events:            <none>

serverService and clusterService is ok.
 
weblogic operator: 3.0.2
wewblogic base image: store/oracle/weblogic:12.2.1.4-dev-200117

**Comment by tbarnes-us** [comment] 2021-03-29 20:09
Definitely looks like a bug.  

@csegedicsaba Do you know if this is till a problem? (It's certainly OK to respond with "I don't know".)

@rjeberhard Any thoughts?

**Comment by tbarnes-us** [comment] 2021-03-29 20:10
Assigned to Ryan for triage...

**Comment by rjeberhard** [comment] 2021-03-29 20:34
I've verified that this is a bug. I'll get someone to fix it.

**Comment by rjeberhard** [comment] 2021-03-29 20:45
[Replacing my original response] The spec.adminServer element has two different children related to services: adminService and serverService. If you want labels on the admin server's ClusterIP service then you need to use spec.adminServer.serverService.labels similarly to what you would do for cluster members. The labels and annotations under adminService are related to the second, optional NodePort service that the operator can create for an admin server channel.

**Comment by csegedicsaba** [comment] 2021-03-31 21:10
I use ClusterIP service, but spec.adminServer.**serverService**.annotations are not working on version 3.1.0.

**Comment by rjeberhard** [comment] 2021-04-13 16:56
I believed that I had tried this earlier and found that I couldn't reproduce the failure. I just tried it also didn't work for me. I'll have someone take another look.

**Comment by rjeberhard** [comment] 2021-04-27 17:54
Fixed in 3.2.2.

**Closed by rjeberhard** 2021-04-27 17:54 UTC
Labels: bug, help wanted
