### ISSUE TITLE
MOUNT PV ERROR, Logs show "Permission denied"

### ISSUE THREAD

**Issue by dai0384448** [oracle/weblogic-kubernetes-operator#1809] opened 2020-07-15 07:15 UTC
/data directory Has authorized oracle:oracle.

[root@k8s-1 uuu-domain]# ll /
total 28
drwxr-xr-x    3 root   root     25 May  9 14:56 apps
lrwxrwxrwx.   1 root   root      7 May 11  2019 bin -> usr/bin
dr-xr-xr-x.   6 root   root   4096 Apr 29 17:12 boot
drwxrwxrwx    4 oracle oracle   66 Jul 14 16:35 data
drwxr-xr-x   18 root   root   3320 May 11 13:59 dev

**The environment is as follows:**

OS: CentOS Linux release 8.1.1911 (Core)
Docker Version: 19.03.8
K8S:Version: 1.18.2
Release operator 2.6.0

**The error is as follows:**

[root@k8s-1 uuu-domain]# kubectl get pod -n sample-domain1-ns
NAME                                     READY   STATUS   RESTARTS   AGE
uuu-domain-introspect-domain-job-dmx8v   0/1     Error    0          59s
[root@k8s-1 uuu-domain]# 
[root@k8s-1 uuu-domain]# kubectl logs uuu-domain-introspect-domain-job-dmx8v -n sample-domain1-ns
@[2020-07-15T06:54:22.792 UTC][introspectDomain.sh:64][FINE] Introspecting the domain
@[2020-07-15T06:54:22.805 UTC][introspectDomain.sh:252][FINE] Env vars before:
    DOMAIN_UID='uuu-domain'
    NAMESPACE='sample-domain1-ns'
    SERVER_NAME=''
    SERVICE_NAME=''
    ADMIN_NAME='admin-server'
    AS_SERVICE_NAME=''
    ADMIN_PORT='7001'
    ADMIN_PORT_SECURE=''
    USER_MEM_ARGS='-Djava.security.egd=file:/dev/./urandom '
    JAVA_OPTIONS='-Dweblogic.StdoutDebugEnabled=false'
    FAIL_BOOT_ON_SITUATIONAL_CONFIG_ERROR=''
    STARTUP_MODE=''
    DOMAIN_HOME='/u01/oracle/user_projects/domains/uuu-domain'
    LOG_HOME=''
    SERVER_OUT_IN_POD_LOG='true'
    DATA_HOME='/data/uuu-domain'
    KEEP_DEFAULT_DATA_HOME=''
    EXPERIMENTAL_LINK_SERVER_DEFAULT_DATA_DIR=''
    JAVA_HOME='/usr/java/jdk-8'
    ORACLE_HOME='/u01/oracle'
    WL_HOME=''
    MW_HOME=''
    NODEMGR_HOME='/u01/nodemanager'
    INTROSPECT_HOME='/u01/oracle/user_projects/domains/uuu-domain'
    PATH='/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk-8/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin::/bin:/u01/oracle'
    TRACE_TIMING=''
@[2020-07-15T06:54:22.820 UTC][introspectDomain.sh:290][FINE] id = 'uid=1000(oracle) gid=1000(oracle) groups=1000(oracle)'
@[2020-07-15T06:54:22.831 UTC][introspectDomain.sh:294][FINE] Directory trace for DOMAIN_HOME=/u01/oracle/user_projects/domains/uuu-domain (before)
  ls -ld /u01/oracle/user_projects/domains/uuu-domain/*:
    drwxr-x--- 2 oracle oracle   24 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/autodeploy
    drwxr-x--- 2 oracle oracle   31 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/backup_config
    drwxr-x--- 6 oracle oracle 4096 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/bin
    drwxr-x--- 3 oracle oracle   16 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/common
    drwxr-x--- 8 oracle oracle  156 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/config
    drwxr-x--- 2 oracle oracle   32 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/console-ext
    -rw-r----- 1 oracle oracle  327 Apr 26  2019 /u01/oracle/user_projects/domains/uuu-domain/fileRealm.properties
    drwxr-x--- 3 oracle oracle 4096 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/init-info
    drwxr-x--- 2 oracle oracle   32 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/lib
    drwxr-x--- 2 oracle oracle   75 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/nodemanager
    drwxr-x--- 2 oracle oracle    6 Apr 26  2019 /u01/oracle/user_projects/domains/uuu-domain/resources
    drwxr-x--- 2 oracle oracle  191 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/security
    drwxr-x--- 3 oracle oracle   34 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/servers
    -rwxr-x--- 1 oracle oracle  260 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain/startWebLogic.sh
  ls -ld /u01/oracle/user_projects/domains/uuu-domain:
    drwxrwxrwx 1 oracle oracle 310 Jul 12 05:50 /u01/oracle/user_projects/domains/uuu-domain
  ls -ld /u01/oracle/user_projects/domains:
    drwxrwxrwx 1 oracle oracle 24 Jul 12 05:50 /u01/oracle/user_projects/domains
  ls -ld /u01/oracle/user_projects:
    drwxr-xr-x 1 root root 21 Jul 12 05:50 /u01/oracle/user_projects
  ls -ld /u01/oracle:
    drwx------ 1 oracle oracle 87 Jul 12 05:50 /u01/oracle
  ls -ld /u01:
    drwxr-xr-x 1 oracle oracle 28 Jun 24 05:33 /u01
  ls -ld /:
    drwxr-xr-x 1 root root 54 Jul 15 06:54 /
@[2020-07-15T06:54:22.861 UTC][introspectDomain.sh:294][FINE] Directory trace for DATA_HOME=/data/uuu-domain (before)
  ls -ld /data/uuu-domain/*:
    ls: cannot access /data/uuu-domain/*: No such file or directory
  ls -ld /data/uuu-domain:
    ls: cannot access /data/uuu-domain: No such file or directory
  ls -ld /data:
    ls: cannot access /data: No such file or directory
  ls -ld /:
    drwxr-xr-x 1 root root 54 Jul 15 06:54 /
@[2020-07-15T06:54:22.883 UTC][introspectDomain.sh:102][FINE] Creating data home directory: '/data/uuu-domain'
mkdir: cannot create directory ‘/data’: Permission denied
@[2020-07-15T06:54:22.896 UTC][introspectDomain.sh:59][SEVERE] Unable to create folder /data/uuu-domain
[root@k8s-1 uuu-domain]#  
[root@k8s-1 uuu-domain]# 
[root@k8s-1 uuu-domain]# 

**The default domain created by the script has the following :**
[root@k8s-1 uuu-domain]-# cat domain.yaml 
-# Copyright (c) 2017, 2019, Oracle Corporation and/or its affiliates. All rights reserved.
-# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
-#
-# This is an example of how to define a Domain resource.
-#
apiVersion: "weblogic.oracle/v6"
kind: Domain
metadata:
  name: uuu-domain
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: uuu-domain
spec:
  -# The WebLogic Domain Home
  domainHome: /u01/oracle/user_projects/domains/uuu-domain

  -# If the domain home is in the image
  domainHomeInImage: true

  -# The WebLogic Server Docker image that the Operator uses to start the domain
  image: "192.168.1.210/weblogic/uuu-domain:12.2.1.4-generic"

  -# imagePullPolicy defaults to "Always" if image version is :latest
  imagePullPolicy: "IfNotPresent"

  -# Identify which Secret contains the credentials for pulling an image
  -#imagePullSecrets:
  -#- name: 

  -# Identify which Secret contains the WebLogic Admin credentials (note that there is an example of
  -# how to create that Secret at the end of this file)
  webLogicCredentialsSecret: 
    name: sample-domain1-weblogic-credentials

  -# Whether to include the server out file into the pod's stdout, default is true
  includeServerOutInPodLog: true

  -# Whether to enable log home
  -# logHomeEnabled: false

  -# The in-pod location for domain log, server logs, server out, and Node Manager log files
  -# logHome: /shared/logs/domain1
  -# An (optional) in-pod location for data storage of default and custom file stores.
  -# If not specified or the value is either not set or empty (e.g. dataHome: "") then the
  -# data storage directories are determined from the WebLogic domain home configuration.
  dataHome: "/data"

  -# Istio service mesh support is experimental.
  -# experimental:
  -#   istio:
  -#     enabled: 
  -#     readinessPort: 

  -# serverStartPolicy legal values are "NEVER", "IF_NEEDED", or "ADMIN_ONLY"
  -# This determines which WebLogic Servers the Operator will start up when it discovers this Domain
  -# - "NEVER" will not start any server in the domain
  -# - "ADMIN_ONLY" will start up only the administration server (no managed servers will be started)
  -# - "IF_NEEDED" will start all non-clustered servers, including the administration server and clustered servers up to the replica count
  serverStartPolicy: "IF_NEEDED"

  serverPod:
    -# an (optional) list of environment variable to be set on the servers
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom "
    -# volumes:
    -# - name: weblogic-domain-storage-volume
    -#   persistentVolumeClaim:
    -#     claimName: domain1-weblogic-sample-pvc
    -# volumeMounts:
    -# - mountPath: /shared/test0710
    -#   name: weblogic-domain-storage-volume

  -# adminServer is used to configure the desired behavior for starting the administration server.
  adminServer:
    -# serverStartState legal values are "RUNNING" or "ADMIN"
    -# "RUNNING" means the listed server will be started up to "RUNNING" mode
    -# "ADMIN" means the listed server will be start up to "ADMIN" mode
    serverStartState: "RUNNING"
    adminService:
      channels:
    -# The Admin Server's NodePort
       - channelName: default
         nodePort: 31701
    -# Uncomment to export the T3Channel as a service
    -#    - channelName: T3Channel

  -# clusters is used to configure the desired behavior for starting member servers of a cluster.  
  -# If you use this entry, then the rules will be applied to ALL servers that are members of the named clusters.
  clusters:
  - clusterName: cluster-dy
    serverStartState: "RUNNING"
    replicas: 8
  -# The number of managed servers to start for unlisted clusters
  -# replicas: 1

[root@k8s-1 uuu-domain]-#

**Comment by russgold** [comment] 2020-07-15 13:41
According to the log, it is unable to create the /data directory. How are your PV and PVC defined?

**Comment by dai0384448** [comment] 2020-07-15 14:32
I don't have a definition, just a local directory specified in the script.Please advise how to define it, thank you!

**Comment by russgold** [comment] 2020-07-15 15:45
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by dai0384448** [comment] 2020-07-22 07:33
After using PVC, the WebLogic cluster can be deployed normally, but when the application is deployed, the directory corresponding to PVC is not selected and empty.


![图片](https://user-images.githubusercontent.com/47651287/88147876-64365400-cc30-11ea-9cbb-9d1a348e08ef.png)
[root@k8s-1 data]# kubectl get pv
NAME                  CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                    STORAGECLASS   REASON   AGE
pv-volume-path-data   10Gi       RWO            Retain           Bound         default/pv-claim-zhrs    manual                  5h29m
task-pv-volume        10Gi       RWO            Retain           Terminating   default/task-pv-claim1   manual                  5d10h
[root@k8s-1 data]# kubectl get pvc
NAME             STATUS        VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pv-claim-zhrs    Bound         pv-volume-path-data   10Gi       RWO            manual         5h29m
task-pv-claim1   Terminating   task-pv-volume        10Gi       RWO            manual         5d10h
[root@k8s-1 data]# 
[root@k8s-1 data]# cat /test/pod/storage/pv-volume.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-path-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
[root@k8s-1 data]# 
[root@k8s-1 data]# 
[root@k8s-1 data]# ll /data/
total 20
-rwxrwxrwx 1 oracle oracle   0 Jul 12 14:26 123123
drwxrwxrwx 2 oracle oracle   6 Jul 12 14:26 3243
-rw-r--r-- 1 root   root   266 Jul 17 05:56 commands.yaml
-rw-r--r-- 1 root   root   257 Jul 17 05:47 cpu-request-limit.yaml
-rw-r--r-- 1 root   root    35 Jul 17 05:13 index.html
-rw-r--r-- 1 root   root   337 Jul 17 05:30 memory-request-limit-2.yaml
-rw-r--r-- 1 root   root   334 Jul 17 05:24 memory-request-limit.yaml
[root@k8s-1 data]#

**Comment by tbarnes-us** [comment] 2021-03-29 21:01
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.

**Closed by tbarnes-us** 2021-03-29 21:01 UTC
