### ISSUE TITLE
Scripts under create-rcu-schema does not support different namespace, DB sys and schema password and uses scott demo user

### ISSUE THREAD

**Issue by ashageetha** [oracle/weblogic-kubernetes-operator#1610] opened 2020-04-29 10:39 UTC
Scripts under create-rcu-schema has below issues and will not work in some use-cases as listed below:
1)  Uses namespace “default” which may not work if the user does not have access to it and need to provide specific namespace.
2) "rcu.yaml" always uses imagePullSecret even if docker-secret is not passed.
3) Both sys and schema database password is hard coded to “Oradoc_db1” and does not give option  to provide different value.
     echo “Oradoc_db1” > pwd.txt
    echo “Oradoc_db1" >> pwd.txt
4) Create and drop rcu schema scripts both uses scott demo user to test the connectivity before proceeding with create or drop schemas which may not be present in fresh install database. Hence need to either use system user.
5) "rcu.yaml" is directly edited and may not be usable to use the same repo for another scenarios.

**Comment by tbarnes-us** [comment] 2021-03-29 21:30
I'm assuming the issue is resolved by now, feel free to re-open the issue if I'm incorrect.

**Closed by tbarnes-us** 2021-03-29 21:30 UTC
